### ISSUE TITLE
MIS Budget 

### ISSUE THREAD

**Issue by fclementic2c** [OCA/mis-builder#102]
Hi @sbidoul 

I fear a big limitation on MIS budget. Tell me if I got something wrong here.

Context:
- A report template can be used by different companies ok... but only if based on same chart of account. (I know that technically it works but we will have funny numbers if your 3% for instance point to a different CoA. Right?)
- A MIS budget can and must have only 1 report template. 

use case: 
A group has companies in France, Switzerland and Germany with 3 different chart of accounts. 
Having 3 different P&L report template is not an issue.
But how can you handle the budget? 
If you create 3 budget (1 for each country P&L template) you cannot go any further to aggregate budgets.
Don't we have an issue on MIS Builder budget assuming that a budget must be linked to only 1 template ?
Even in mono-company environment, it means that you can see your budget through only 1 report. A department manager cannot have his own department report then.

In my view, we miss 1 model between the kpi and the budget item (let's call it Budget account) 
We would need to be able to map a KPI  to a Budget item account (this budget account would be shared cross company).

What's your opinion Stéphane ? Do you agree ? Does it sounds technically do-able ? and, If yes, would it be a big job ?

Thanks

Frederic

**Comment by fclementic2c** [comment]
just thinking further:
that would suppose that instead of a flag on line expressions you would have to choose a budget account.
Or (but much more complex) we would need possibility to build report template based on budget accounts.

**Comment by sbidoul** [comment]
Not looked in details to your question yet, but a first hint:

> only if based on same chart of account

This is true only if you base the report template on account codes.

You can also create reports based on, say, account tags, eg `bal[('tag_ids...', '=', '...')]`.

**Comment by fclementic2c** [comment]
@sbidoul Yes, but I recently discovered that if you base you KPI on tags you cannot use subkpi based on operating units or analytic tags :|

**Comment by sbidoul** [comment]
> if you base you KPI on tags you cannot use subkpi based on operating units or analytic tags

That needs to be investigated. Can you open a separate issue about that?

For the rest the fundamental philosophy of mis budgets is that we budget on KPIs (+ possibly analytic dimensions). It is useful for instance if you want to budget on non accounting data (eg budget on a number of employees, or similar). I'm not too sure how a concept of budget account would fit into that.

If you want to do consolidation with different chart of accounts, using account tags or types is the way to go.

Regarding budget by department, in our use cases, the department is an analytic dimension, so it's the same mis report template, and we use "analytic" filters to show the mis report per department. I guess it's the same for you. It should work the same with operating units.

Note that we have not investigated multi company consolidation for budgets yet. There is #34 to track that. It should not be very difficult.

**Comment by fclementic2c** [comment]
@sbidoul 
We are migration our own instance to odoo11.
We want to use MIS to create our P&L with department in column (sub-kpi).
Our deportments will be handle with analytic tags.
Since our P&L template will be used in 3 different countries we cannot based our KPIs formulas on accounts. So we want to use account tag instead.

So I am trying to build my report with a formula like : balp[][('account_id.tag_ids', '=', ref('__export__.account_account_tag_31').id),('analytic_tag_ids’, ’=’,ref(‘__export__.account_analytic_tag_1’).id)]

![image](https://user-images.githubusercontent.com/5735158/48854684-c8957600-edb2-11e8-8267-c29e1adc6786.png)

![image](https://user-images.githubusercontent.com/5735158/48854710-d77c2880-edb2-11e8-8302-14a647ce80e9.png)

When I launch the report I get an error:
File "/opt/odoo/src/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/src/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/src/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/src/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/src/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/external-src/mis-builder/mis_builder/models/mis_report_instance.py", line 747, in compute
    kpi_matrix = self._compute_matrix()
  File "/opt/odoo/external-src/mis-builder/mis_builder/models/mis_report_instance.py", line 725, in _compute_matrix
    self.query_company_ids, self.currency_id)
  File "/opt/odoo/external-src/mis-builder/mis_builder/models/mis_report.py", line 536, in _prepare_aep
    aep.parse_expr(expression.name)
  File "/opt/odoo/external-src/mis-builder/mis_builder/models/aep.py", line 181, in parse_expr
    _, mode, acc_domain, ml_domain = self._parse_match_object(mo)
  File "/opt/odoo/external-src/mis-builder/mis_builder/models/aep.py", line 167, in _parse_match_object
    ml_domain = tuple(safe_eval(ml_domain, domain_eval_context))
  File "/opt/odoo/src/odoo/tools/safe_eval.py", line 299, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/opt/odoo/src/odoo/tools/safe_eval.py", line 156, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    [('account_id.tag_ids', '=', ref('__export__.account_account_tag_31').id),('analytic_tag_ids’, ’=’,ref(‘__export__.account_analytic_tag_1’).id)]
                                                                                                                                                             ^
SyntaxError: EOL while scanning string literal

@sbidoul We are willing to implement this feature but we do not know if it make sens and how complex it could be.
What do you think about this ?

Thanks

Frederic

**Comment by sbidoul** [comment]
A wrong quote somewhere in the expression. '`‘

**Comment by fclementic2c** [comment]
@sbidoul  Ok let me hide under the table
my single quote was modified by Libreoffice I think as I have imported csv files.

But It works... Awesome !

**Comment by sbidoul** [comment]
@fclementic2c can we close this one?
