### ISSUE TITLE
Ventilation of operating profit by analytical axis

### ISSUE THREAD

**Issue by beatrice-legendre** [OCA/mis-builder#106]
Hello,
I'm taking over the MIS Builder module that can do a lot of things (thank you !).
I was able to build a P & L and I would need to be able to zoom in / out on different levels of cost accounting (results of the company overall / by business area / by activity ...). Does the Business Analytic Filter module that you plan to put in v. 3.3 (if I understood correctly) will be able to answer this need? 
Will the solution be to duplicate the report as many times as I need levels of analysis? Or is it the same report for which you have to go to edit mode to change the Filters tab?
Do you have any idea of ​​when you expect to release v3.3 ?

Sorry, many questions ... but thank you alot in advance for your answers !

**Comment by sbidoul** [comment]
Hello, thanks for using mis builder.

The analytic filter mechanism (#24) shows a combo box at the top of the preview, so the user can select what analytic account he wants to filter on.

I've no precise idea when it will be released. #24 works fine, but there is some fine tuning to do before I consider it good enough to merge and support in the long term. Waiting for available time and/or funding or our next project that will need that module.
