### ISSUE TITLE
Purchase order authorisation based on MIS Builder budget item

### ISSUE THREAD

**Issue by jackjack82** [OCA/mis-builder#110]
Dear all, 
 we are using MIS builder for business reporting and analysis via KPIs. Great tool, thank you for your work.

Our client is now asking to have the acqusition authorization process based on the budget created in MIS Builder.  Does anybody already had to satisfy a similar request? 

At present, the solution we have been thinkng is the following: before order confirmation we ask the user to select the overall MIS builder Instance and the related budget item (It would be hard to use the accounts on the order's product to find the proper budget item/KPI). The module shall then compute the value of the KPI related to the budget item at the specific date and return the availalable amount.

It does not look easy ;)  Any suggestions?

Thank you in advance for your time.

Giacomo

**Comment by sbidoul** [comment]
Yes it is feasible. I'll try to give you some pointers.

One of those is `get_kpi_by_account_id()` to find the right KPI from the GL account.

https://github.com/OCA/mis-builder/blob/515290d86c10fd02892420cb30dcd167fba0831d/mis_builder/models/mis_report.py#L823

**Comment by sbidoul** [comment]
To elaborate a bit on this question, here is a possible approach to do this:

- create a report with a column (`mis.report.instance.period`) showing available budget (this column should typically being of type "sum", showing budget minus actuals, minus committed)
- have some kind of flag to mark which `mis.report.instance.period` corresponds to the "current" available budget (the above column)
- when validating a purchase order (or purchase request) use `get_kpis_by_account_id` to find the KPI corresponding to the GL account of each PO line
- use `mis.report.instance.compute()` to evaluate kpis, find the "current" available amount for period/kpis and report a warning or block if not enough budget is left

Not exactly trivial but all building blocks are there.
