### ISSUE TITLE
Process finished with exit code -1073740777 (0xC0000417)

### ISSUE THREAD

**Issue by westlyou** [OCA/mis-builder#113]
please help me 
click  "preview" button,then threw error "  Process finished with exit code -1073740777 (0xC0000417)"

**Comment by sbidoul** [comment]
There is really too little information in your problem description. You need to provide full details of what you are attempting to do and, in particular which Process crashes (is it Odoo? your browser?)...

**Comment by sbidoul** [comment]
Closing since there is no answer, feel free to reopen when you have a description of your issue.
