### ISSUE TITLE
hidding non value lines

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/mis-builder#119]
Hi is posible to hide a non value lines in a sub-kpi?
For example have a kpi with sub-kpi:  bale | bale[146%]
No result returned and want to hide this kpi on a report.

**Comment by sbidoul** [comment]
Look for MIS Report Styles: they have "Hide empty" and "Hide always" properties. You can then assign styles to KPIs.

**Comment by pepitovadecurt** [comment]
Thanks for your comment but not run for me. 
On a blank report asign a new style with all options of Visibility enabled. The lines without value are still showed. 
Have a ODOO 10.0, MIS Builder 10.0.3.2.1 and QWeb Financial Reports 10.0.1.2.0

**Comment by sbidoul** [comment]
You'll need to provide more details on your specific case, as this function is known to work correctly in many situations.

**Comment by pepitovadecurt** [comment]
Here is a few of captures:
![imagen](https://user-images.githubusercontent.com/42767320/44719202-d5ac0d00-aac2-11e8-8452-5139b946bd5e.png)
![imagen](https://user-images.githubusercontent.com/42767320/44719240-fa07e980-aac2-11e8-9c0a-d555722f8f75.png)
![imagen](https://user-images.githubusercontent.com/42767320/44719255-055b1500-aac3-11e8-8610-c1fdd9541d55.png)
![imagen](https://user-images.githubusercontent.com/42767320/44719277-14da5e00-aac3-11e8-9225-192d2c2c518f.png)

**Comment by sbidoul** [comment]
One thing is strange: "Hide always inherit" and "Hide always" are both checked. Normally, "Hide always" should not be visible if "Hide always inherit" is checked, as for the other style elements.

**Comment by pepitovadecurt** [comment]
Now runs perfectly! 
When unchecked "Hide null inherit" appears "Hide null" and with this option the line not showed when null.
Many thanks sbidoul.

![imagen](https://user-images.githubusercontent.com/42767320/44721248-8fa67780-aac9-11e8-9eb1-3e502d90c0d0.png)

**Comment by sbidoul** [comment]
@pepitovadecurt I fixed the bug related to the visibility of then "Hide always" checkbox. in #121. You may want to review it.
