### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#12]
Migrate dependencies:
- [x] web_widget_color (in OCA/web) https://github.com/OCA/web/pull/777
- [x] date_range (in OCA/server-tools)
- [x] report_xlsx (in OCA/reporting-engine) https://github.com/OCA/reporting-engine/pull/171

Procedure
- [x] 1. merge #1 in 9.0
- [x] 2. merge 9.0 in 10.0 and adapt
- [x] 3. create 11.0 branch from 10.0 and make modules uninstallable
- [x] 4. do whatever is needed to adapt to 11.0 #67 (please create PR's to branch 11.0-dev to contribute)

Note all python 3 compatibility changes that can be made in a python 2 compatible way should be made on the 10.0 branch to facilitate forward porting of future evolutions.

**Comment by pedrobaeza** [comment]
I renamed the title for complying with current naming generated by the script.
