### ISSUE TITLE
Budgeting sales opportunities?

### ISSUE THREAD

**Issue by tuomoaura** [OCA/mis-builder#122]
Hi,

Can I budget sales opportunities with these modules (and how)? 
I'd like to have the actuals from the opportunity and then compare those to budget per sales person (divided into sales teams) per month.

PS. Thank you for the great work!

**Comment by sbidoul** [comment]
You would need to create one Query (in the Queries tab) per sales person that fetches data from crm.lead. Then create sum KPIs for each sales team. Then use these KPIs in your budget. If you have a limited number of Sales persons it should work.

**Comment by tuomoaura** [comment]
@sbidoul Thank you for the answer! 

That was exactly my idea but cannot find crm.lead in the Model dropdown. I was testing this with http://3337645-11-0-68080b.runbot1.odoo-community.org/web?debug=1#id=34&view_type=form&model=mis.report

**Comment by sbidoul** [comment]
That's strange, there is no filter in that drop down IIRC.

**Comment by tuomoaura** [comment]
@sbidoul Haha, because CRM module is not installed :)  Sorry!
