### ISSUE TITLE
Code of templates

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/mis-builder#124]
Hi just defined a few MisReports templates and need to export and modify.
Cannot find it in Configuration->Technical->Reports
Exporting the template the KPIs not exported.

Any recommendation?

**Comment by sbidoul** [comment]
It is possible to do a CSV/Excel export of MIS Report Templates using the standard Odoo feature. Alternatively you can create them in a data module (such as https://github.com/OCA/l10n-belgium/blob/10.0/l10n_be_mis_reports/data/mis_report_pl.xml).

**Comment by pepitovadecurt** [comment]
Thanks sbidoul, I am rewriting the xml following my needs. A great system of reports!
