### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by mokerosan** [OCA/mis-builder#131]
I have this error when I update from version 10.0.3.2.1 (2018-05-29) to 10.0.3.2.2 (2018-06-30), any idea why this happens?

`  File "/opt/odoo/odoo11/odoo/models.py", line 428, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)

TypeError: Model 'report' does not exist in registry.`

**Comment by sbidoul** [comment]
Aren't you trying to install mis builder 10.x on Odoo 11? That's not going to work.

**Comment by sbidoul** [comment]
Closing for lack of feedback.
