### ISSUE TITLE
[RFC] mis_builder_analytic: New module for querying analytic entries

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/mis-builder#135]
We are going to develop a module for this task, with the following initial thoughts:

* Create an SQL view with an associated model with `_auto = False` for getting the structure needed to fit mis_builder (debit, credit, date and so on fields).
* Create a template with a example mis.builder.report that uses that query.

@sbidoul AFAIK, for using that model, you have to add a record mis.builder.report.query record in the template. Is this true? If so, I see this very inconvenient and I think we should have a query template possibility for easing the use of other models. It can be in our budget to add this possibility.

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza ,

Sounds good. Let me know if you need any (functional) help.

**Comment by sbidoul** [comment]
> you have to add a record mis.builder.report.query record

That is not necessary. If the model has the [right columns, you simply use the Actuals (alternative)](https://github.com/OCA/mis-builder/blob/4f8aba75554a7aaf4713ecdbb7e23a3c3d8542b7/mis_builder/models/mis_report_instance.py#L219-L243) source.

**Comment by sbidoul** [comment]
BTW, as discussed with Gonzalo Ruzafa at the LLN code sprint, I plan to create a new mis-builder-contrib repo where such addon modules can go and follow a looser migration regime (different than the core module where I continue to apply the strict backport/forward port to all supported versions).

**Comment by sbidoul** [comment]
@pedrobaeza What would be the columns of that view?

**Comment by pedrobaeza** [comment]
@sbidoul I don't think we need such granularity in repositories, as this module can fit here, but that's not the main problem I think.

About the columns, I'm not developing this and my colleague will investigate, but I remember that the needed ones are `date`, `debit`, `credit`, but I'm not sure right now how to handle accounts part. Maybe is enough to link to a table with `code` and `name`?

About the "Actuals (alternative)", it's a bit weird to require to enable comparison mode, add a period, and there select "Actuals". Do you think reasonable to add a field "Actuals (alternative)" at mis.builder.report.instance level that if not filled, it acts like now, but if filled, we change the source?

**Comment by pedrobaeza** [comment]
Closing this as it's merged in https://github.com/OCA/mis-builder-contrib/tree/11.0/mis_builder_analytic
