### ISSUE TITLE
Analytic filter in report columns definition

### ISSUE THREAD

**Issue by bunhin** [OCA/mis-builder#138]
I have a question,
is it possible if i have a kpi lines and want to display the total for each analytic account together as columns?, I mean each analytic account as a column in the report and displayed together and then put other period data as second row as the comparison such as below :

KPI and period                           analytic acc-1      analytic acc-2 analytic acc-3  ..and so on     Total

expenses                                   total an-acc-1      total-an-acc2  Total-an-acc3  ...and son       Total
expenses other period               total an-acc-1-op   ...........             ................... 

How to achieve this if it is possible with current state of mis-builder. Thank you

**Comment by HaraldPanten** [comment]
Hi @bunhin ,

In my opinion, it shouldn't be posted as an issue, as it is a question...

I'm not sure if it's possible to do this with the new functionallity; filtering by analytic account. 

But, I'm pretty sure that it can be done using Sub KPI's functionallities.

Try something like:

                          Period 1                                              Period 2                                    ...
         an. acc. 1   an. acc. 2  an. acc. 3         an. acc. 1  an. acc. 2  an. acc.3         ...   ...   ...

KPI 1

KPI 2

KPI 3

....

Am I right @sbidoul ?

**Comment by bunhin** [comment]
Hi @HaraldPanten, yes it should be posted as question, i am sorry for not put the question label
Thank you for response and may be i need to explore further with the sub.kpi if so.  My understanding at current state the column is should be defined (not dynamically added as number of analytic account grows for example) but it is for child rows detail

**Comment by sbidoul** [comment]
Hi,

I'm fine with questions in github issues. I'm adding the question label when needed, no worries.

Using subkpi can work, if you use the move line filter in expression such as `balp[][('analytic_account_id.code', '=', 'XYZ')]`.

Another way to do it would be to add an analytic filter field on `mis.report.instance.period`, similar to what is done in [mis_builder_operating_unit](https://github.com/OCA/operating-unit/blob/10.0/mis_builder_operating_unit/model/mis_builder.py). 

I think it makes sense to have that in the core mis_builder module, and I'm willing to review a PR about that.

So I'm adding the enhancement label :)

**Comment by HaraldPanten** [comment]
Cool, thx!

**Comment by bunhin** [comment]
Hi again,
Thanks to @sbidoul 
One more question, is it possible to have a column that calculate percentage of a kpi line value of a period, **to a selected** other kpi line value on the same period.
sample of use case:
When people generate a PnL report for example,  it is frequently wanted to see each line  value to the total sales value for example.

or if  a kpi line is a sum total of   2 or more  other kpi line,   then each kpi line contribute how many % to the sum total. of course this can be done via export to excell then do the calculation there, probably the feature already in the core 

If it is possible with the current state, then please inform how to achieve it. thank you

**Comment by sbidoul** [comment]
@bunhin please don't mix different topic in the same issue.

For what you want to do, you can simply reference other kpis by their name (eg with an expression such as `profit / revenue`).

**Comment by bunhin** [comment]
Hi @sbidoul, thank you, and  i believe i need to post this in new thread, since i don't get it yet

**Comment by vdewulf** [comment]
Hi @sbidoul 
Hope you're well!
I have the same question: how to have 2 or more columns on a report, each colomn corresponding to an analytic account.
I don't get your answer: "Using subkpi can work, if you use the move line filter in expression such as balp[][('analytic_account_id.code', '=', 'XYZ')]."

=> I don't understand how to create subkpi's even reading the documentation
https://oca-mis-builder.readthedocs.io/en/latest/usage.html#sub-kpi

Is there someone functional available to explain the whole logic behind Kpi? or even build with me a P&L report with subKpi's corresponding to analytic accounts?
I could in exchange give some documentation to the commynity :)
Thanks!

Thanks a lot!

**Comment by sbidoul** [comment]
@vdewulf I would not recommend using sub-KPIs for this.

Instead try out #261 which allows you to create explicit analytic filters for each column.

Looking forward to reading your feedback on that feature.

**Comment by sbidoul** [comment]
Done in #261
