### ISSUE TITLE
[V10] template import always get 'Unknown error during import: ...'

### ISSUE THREAD

**Issue by bunhin** [OCA/mis-builder#139]
Hi,
I just try to import a report template that i prepare using excell sheet as well as opencalc sheet with csv format, but always get error when validating before import with the following message
"Unknown error during import: <class 'odoo.exceptions.ValidationError'>: Error while validating constraint The name must be a valid python identifier between rows 2 and 33
Resolve other errors first"  2 and 33 mean whole line.

I suspect the expression formula is not allowed to import since there are some '+' operators as well as many balp[nnn.%],  i have tried to not import the column containing those, but still the error persistence.

i believe the csv file is good.
is there a clue what may cause this error?

Thank you

**Comment by sbidoul** [comment]
> The name must be a valid python identifier between rows 2 and 33

This is the kpi technical name that must be wrong in your file.

**Comment by bunhin** [comment]
oh yes, mis typed wrong character - instead of _, thankyou @sbidoul , i close this issue.  Thanks again
