### ISSUE TITLE
Question, how to refer to parent KPI for sub kpi expression, no example found in help tab

### ISSUE THREAD

**Issue by bunhin** [OCA/mis-builder#141]
With the Demo ExpensesTemplate, i add 2 sub KPI  for example  "value" and "percentage_to_total" then check on the "multi" to entry the expression for all 4 kpi's; "Expenses", Equipment", "Others", and "Total" ,  to simplify on the report i delete the "budget", also the "commited" and "available" column

for value subkpi_id expression on "Expenses KPI"   i put  value = balp[NN%]
for percentage i want to calculate  as percentage to the value of the "Total" KPI, I did try some for expression line like 
percentage_to_total  = exp.value / total.value * 100
percentage_to_total  = exp / total * 100

but i always get the #NAME error, on the percentage_to_total column as well as on "total" value column

Please inform how to refer to the the total value as divider to get the percentage in this example.
May be it is worth to add some example on the "KPI expression help" tab
  
thank you

**Comment by HaraldPanten** [comment]
Hi @bunhin ,

Could you add some screenshots, please?

THX!

**Comment by bunhin** [comment]
Hi @HaraldPanten 

here are some screen shot
![image](https://user-images.githubusercontent.com/7310629/48850369-16be6f80-eddb-11e8-8c67-ab3e8575ab65.png)

![image](https://user-images.githubusercontent.com/7310629/48850510-7288f880-eddb-11e8-99ee-2c3279be9bf9.png)

in the "Percent" column of each periode  the wanted value is the percentage to the "Total" value  of each respective

**Comment by HaraldPanten** [comment]
Hi @bunhin ,

You can't select different value types in the same KPI line, I think...

Maybe you could try something like:

SUBKPI 1, expression -->  balp[5%]
SUBKPI 2, expression -->   (balp[5%]/**total**)*100     

For SUBKPI 2, **total** must be numeric, so, you can put other computed expressions or a numeric value, for example:

(balp[5%]/**500000**)*100

or 

(balp[5%]/**(balp[5%]+balp[6%]+balp[7%])**)*100

The result is not going to show **%** sign, but you can put a relevant name for the subKPI 2. Something like **Percentage**, or **percent** as you have already done.

**Comment by bunhin** [comment]
Hi @HaraldPanten 
Thank you for the clue, but not yet really answer my point, off course if we put this  (balp[5%]/(balp[5%]+balp[6%]+balp[7%])) to get the total value in "Value" column will works because we write down again for all the expression,  my point is how do we get it just by sum the sub total by referring to other kpi   such as "exp + equip+ other" when no sub kpi.   The point is if the kpi lines are so many it is not efficient if we need to put all the expression components just to get the sub total or total.

It is mentioned in the help expression tab, that we can refer to other kpi, subkpi or query,  but not any sample or clue to do that. 

Thank you  

and   this does not work either      "SUBKPI 2, expression --> (balp[5%]/total)*100"

**Comment by HaraldPanten** [comment]
I'm not sure if you can reffer to a KPI name in a SUBKPI expression.

@sbidoul , what would you say? Do you have any example?

THX!

**Comment by sbidoul** [comment]
With the screenshots it's easier indeed.

The total expression should be ok. Can you hover the mouse on `#NAME` on the total line to reveal the error?

It is possible to reference subkpis of *other* kpis by name. That why the Total expression should work as you wrote it, and I'm curious to know what the error is. It is however currently not possible to reference other subkpis of the same kpi in an expression. 

Moreover subkpis have all the same properties (eg suffix, prefix).

So you can do it as @HaraldPanten suggests above https://github.com/OCA/mis-builder/issues/141#issuecomment-440851107, or put the percent values in separate rows.

**Comment by bunhin** [comment]
Hi @sbidoul , here are the screen shots:
1. The sub kpi
![image](https://user-images.githubusercontent.com/7310629/48899995-b9cac400-ee83-11e8-96c6-ce1ef5695818.png)

2. The Kpi
![image](https://user-images.githubusercontent.com/7310629/48900036-d36c0b80-ee83-11e8-8e6b-ff04090f7a1b.png)
In the picture depicted that for each rows i put several form of expressions to see if any of them will give no error
3. Here is the preview:
![image](https://user-images.githubusercontent.com/7310629/48900295-90f6fe80-ee84-11e8-96d1-e4b26ecbe3f1.png)

4. Here are the preview error message when cursor placed over the #NAME
![image](https://user-images.githubusercontent.com/7310629/48900557-44f88980-ee85-11e8-9bd0-7ff942bd303c.png)

![image](https://user-images.githubusercontent.com/7310629/48900568-4c1f9780-ee85-11e8-946d-fdbc29128f24.png)

![image](https://user-images.githubusercontent.com/7310629/48900691-ade00180-ee85-11e8-9f60-eb473be6bacf.png)



We can see that all form of expression giving the #Name error, 

So what is the correct syntax to refer or get value of other kpi/ rows / column where subkpi is active?

**Comment by bunhin** [comment]
other trial  with  expression  value = exp.value + equip.value  + other.value for "Total" KPI  as below screen shot:
![image](https://user-images.githubusercontent.com/7310629/48902199-6c9e2080-ee8a-11e8-8bd8-b989d295b0db.png)

and here is the error message in the NAME:

![image](https://user-images.githubusercontent.com/7310629/48902230-8ccddf80-ee8a-11e8-8811-3a33da14ddb9.png)

so it stll not recognize exp  or even  value

**Comment by bunhin** [comment]
hi @sbidoul , any clue on above error? what do i have miss in the template?

**Comment by lili94** [comment]
Hi @binhin can you tell how to use subkpi to get result  from other report

**Comment by bunhin** [comment]
Hi @lili94, 
So far as i know/tried before, referring to other report instance is not yet supported, may be others can update on this. Even referring to other sub kpi in same report instance still get error as above
