### ISSUE TITLE
Simplify formulas with subkpis proposition

### ISSUE THREAD

**Issue by fclementic2c** [OCA/mis-builder#142]
Since https://github.com/OCA/mis-builder/issues/114, I propose to add in the subkpis tab the possibility to specify the xml id related the the column.
ie:  
![screenshot-localhost-8069-2018 11 22-17-24-10](https://user-images.githubusercontent.com/5735158/48914361-82f0b000-ee7b-11e8-84d2-53c5a9fd939e.png)

Then, this would be automatically added in the kpi expression when multi is checked.
The idea would be to display only one expression per kpi instead of this:

![screenshot-localhost-8069-2018 11 22-17-26-27](https://user-images.githubusercontent.com/5735158/48914431-c0553d80-ee7b-11e8-8105-ab5142c3def1.png)

@sbidoul good or bad idea ?

Thanks

**Comment by sbidoul** [comment]
I don't understand... can you reformulate?

**Comment by fclementic2c** [comment]
@sbidoul, I can try...

In my example, I create a P&L with 5 subkpis (=column). (Subkpis are our departments and I use analytics tags to identify them).

So for each kpis (= P&L lines) I have to create 5 expressions... This is too fastidious and messy to read

I mean that when you use subkpis, you always have to select "Multi" checkbox in the kpis expressions
meaning  that you always need to integrate in the kpis expression the subkpis id 

![image](https://user-images.githubusercontent.com/5735158/48932919-7bbeb600-eefe-11e8-9851-c4cd9d907112.png)
Note:  analytic tag id (because I use this field to identify department in this example)

What I would expect is a matricial rational.. 
I would specify my subkpis ids, my kpis expressions then MIS create the Multi kpis view automatically.

Is it more clear ?
My fear is that I am too much focus on P&L reports and this mechanism may prevent from flexibility for other king of reports. This is why I wanted to have you feedback.

**Comment by sbidoul** [comment]
@fclementic2c I understand now.

Your case is indeed special in the sense all your subkpis have the same expression except for an additional analytic filter in the domain. In most cases, subkpis have different expressions (such as a trial balance which has subkpis for initial, ending balance and variation).

So one solution is to implement #138, so you would not need subkpis, just different columns. It is similar to `mis_builder_operating_unit`, except it can go in the core mis_builder module.

BTW, I strongly recommend you write your expressions with the account selector in the first `[ ]`: `-balp[('tag_ids, '=', ref(account tag))][('analytic_tag_ids', '=', ref(analytic tag)]` it will be much much more performant.

**Comment by fclementic2c** [comment]
ok, I see. I drop this dev then. Many thanks
