### ISSUE TITLE
Show year on column header

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/mis-builder#145]
Have ODOO 10 comunitty. Is posible to show only the year in the header? Or show only date period without "from" and "to"?
```
<t t-foreach="matrix.iter_cols()" t-as="col">
   <t t-if="col.description">
      <t t-esc="col.description"/>
   </t>
</t>
```

**Comment by HaraldPanten** [comment]
Hi @pepitovadecurt it's really easy, you need to follow these steps:

Step 1: Go to Accounting --> Reports --> MIS reports.

Step 2: Create a new one. Select the name, the template...

Step 3: You have to select the checkbox "Comparison mode" and you'll realise that a new tab (Columns) appears.

Just create the columns you need. The name of the columns (of the headers in the report) is going to be the one that you write in the "label" field.

See attached screenshots.

<img width="1019" alt="captura de pantalla 2018-12-06 a las 1 50 25" src="https://user-images.githubusercontent.com/32449357/49553821-c5919e00-f8f9-11e8-8ced-0749bb1ac141.png">

<img width="1425" alt="captura de pantalla 2018-12-06 a las 1 58 12" src="https://user-images.githubusercontent.com/32449357/49554004-8e6fbc80-f8fa-11e8-8ac4-b1f73d3cbcec.png">


**PS: Remember to use the last version of MIS builder**

**Comment by pepitovadecurt** [comment]
Thanks! Now testing to put the year dynamicaly base on the pivot date. Any idea?

**Comment by HaraldPanten** [comment]
Could you give me more details? I don't understand what you're trying to do. A Screenshot would be nice.

THX!

**Comment by sbidoul** [comment]
@pepitovadecurt If you tick `Display Columns Description` in the Layout tab, you will get from/to dates displayed in the column headers.
