### ISSUE TITLE
MX Fiscal requirement for reports:   Execution date/time, a more descrptive title and footnotes.

### ISSUE THREAD

**Issue by hectorHerreraTeigeiro** [OCA/mis-builder#146]
Due to fiscal requirements MX fiscal and accounting reports must have:   Execution date/time, a more descriptive title and footnotes.     How can they be added to the PDF output?

**Comment by sbidoul** [comment]
Let's try to split this issue.

- Footnote is tracked #159 
- What would you like for a more descriptive title (can you open another issue to track that)?
- Regarding execution date/time, could it be handled with regular Odoo report header/footers?

**Comment by hectorHerreraTeigeiro** [comment]
A more descriptive title will have:   Report name, Company name, Date range, Currency.       
I have manually added date range and currency to the report name, it is a fast solution, but it would be ideal to have the date range and currency from the report parameters.
About execution time, it works fine with the header option.

**Comment by sbidoul** [comment]
Report name is the report title. Company name is added automatically next to the title.

For mis builder, the date ranges are in the column titles.

The execution date time is tracked in #193 

Currency is missing indeed.
