### ISSUE TITLE
Version 11 or 12?

### ISSUE THREAD

**Issue by eggu68** [OCA/mis-builder#147]
In branch 12.0, module mis_builder, the __manifest__.py module still says it is version:

{
    'name': 'MIS Builder',
    'version': '11.0.3.2.2',

Is this the reason it can't be installed to Odoo 12?

**Comment by HaraldPanten** [comment]
Hi @eggu68 ,

MIS-builder still not installable (installable = false in manifest).

It hasn't been migrated to V12 yet.

**Comment by sbidoul** [comment]
As @HaraldPanten says. 

There are difficulties in migrating the last javascript changes to v11 that need to be resolved first.
