### ISSUE TITLE
Access to KPIs from other reports in KPI expressions, aka subreports

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#155]
A report template `mis.report` can have access to KPI's provided by other reports templates.

This would mean, for example, that you could define a MIS Report for a "Balance Sheet", and then have another MIS Report "Balance Sheet Ratios" that fetches kpi's from "Balance Sheet" to create new KPIS for the ratios (e.g. Current Assets / Total Assets).

Design ideas:
* on `mis.report` add a list of dependent reports, each with a name
* when evaluating a report (in `declare_and_compute_period`), add recursively evaluate dependent reports to add entry in `locals_dict` for each of them
* investigate the impact on mis_builder_budget

In the example above, the ratios report could then have expressions such as `balance_sheet.current_assets / balance_sheet.total_assets`).

**Comment by sbidoul** [comment]
#153 for v8

**Comment by ska-ibees** [comment]
@sbidoul 
It might be wrong place to ask. But could you please confirm below:
Is it possible to use value of a KPI (computed value from mis report) in another model?

Actually I am trying to create a mis report to calculate total fixed expenses of last month and to use this value in pricelist to calculate final price of a product.

Any example code will be highly appreciated.

Thanks

**Comment by sbidoul** [comment]
@go4site this is a different topic. Can you open another issue for this question?

**Comment by ska-ibees** [comment]
@sbidoul #160 created as advised. 
Awaiting for your kind comments please...

Thanks in advance.

**Comment by mileo** [comment]
Hi, we plan to port v8 feature to v12. 

Can we follow the same approach? Any suggestion?

Thanks in advance

**Comment by sbidoul** [comment]
done in #256
