### ISSUE TITLE
Access to KPI value to use in other models

### ISSUE THREAD

**Issue by ska-ibees** [OCA/mis-builder#160]
@sbidoul As advised, same question in a new issue.

Question:
Is it possible to use value of a KPI (computed value from mis report) in another model?

Use case:
Actually I am trying to create a mis report to calculate total fixed expenses of last month and to use this value in pricelist to calculate final price of a product.

Creating MIS report is straight forward. Thanks for the demo module and provided documentation.
However, not getting any clue to get and use KPI's value into another model. 

Would apprecaite any help in this regard. 

Thanks.

**Comment by sbidoul** [comment]
@go4site The [evaluate](https://github.com/OCA/mis-builder/blob/c3d0a2910bdcc3eb00e214745aa80c3797d9c8f1/mis_builder/models/mis_report.py#L856) method of `mis.report` should help.

Don't forget to do performance tests. While it is fast enough for interactive display of a report, it might not be enough for including in price list calculations. This depends on many factors.

**Comment by ska-ibees** [comment]
Thanks a lot for the help.

**Comment by lili94** [comment]
hi @go4site do you have any idea how to create tow colomun with different expression please

**Comment by ska-ibees** [comment]
Hi, Please share some more info as what you need to accomplish?

**Comment by lili94** [comment]
Thanks @go4site  ,in my active balance sheet I have 2,coloumn with different expressions each one have his account for example 
Coloum1_2019brut_capital Emis pbal70
Column 2 net  pbal890 in the same line
