### ISSUE TITLE
[10.0] Expand information by tag or product category

### ISSUE THREAD

**Issue by lauracvilla-zz** [OCA/mis-builder#164]
Hi, It is possible to expand information for a account by tag or maybe product category, for example:
bal[41%] expand accounts detailed information will be show information right now like this:
4115   X1$
4120   X2$
4130   X3$

And if I need information in this way:
bal[41%] movements of this account by ordered by Tag or Product Category
Category A      Z1$
Category B      Z2$
Category C      Z3$

It is possible to do? Thanks

**Comment by sbidoul** [comment]
@lauracvilla this is not supported at the moment. It's a complex topic. There is some discussion about this in https://github.com/OCA/mis-builder/issues/115.

If you don't mind I'll close this issue since this is more or less a duplicate of #115. Feel free to reopen if you feel it's not.
