### ISSUE TITLE
Setting Report from-date to year start ("Year-to-date")

### ISSUE THREAD

**Issue by alyngsoe** [OCA/mis-builder#165]
We often need to specify a report column as "Year-to-date", meaning:
From date: first day of the actual year (from base date)
To date: Base date
Is there a way to do this ?

![year-to-date](https://user-images.githubusercontent.com/12607073/53232076-9c77e280-368a-11e9-9050-69231926e0e6.png)

**Comment by sbidoul** [comment]
From the top of my head, this is not currently possible in an automated way. You need to adjust the end date manually.

**Comment by sbidoul** [comment]
Closed via #194
