### ISSUE TITLE
Is mis-builder restricted to accounting ?

### ISSUE THREAD

**Issue by Maurice67205** [OCA/mis-builder#166]
I tried to add a query in a report model and I wanted to count all male/female employees
I was trying to setup a query with a domain 'male' or 'female' and I would like to count the number of occurrences 
Could not find out how it works

**Comment by djulien19** [comment]
Hello,
MIS is not restricted to accounting.
In Queries from MIS Report Templates, you can select a model and then the field to catch, with the selection of a date.

![image](https://user-images.githubusercontent.com/6325713/65893853-00912080-e3a9-11e9-893b-9dc8f851371d.png)

Then, you add the KPIs wanted.
