### ISSUE TITLE
Question, How to create a domain showing only records that are related to an account_analytic_tag?   As far as it is a many-to-many relation there is no field in account_move_line to map it.

### ISSUE THREAD

**Issue by hectorHerreraTeigeiro** [OCA/mis-builder#167]
Question, How to create a domain showing only records that are related to an account_analytic_tag?   As far as it is a many-to-many relation there is no field in account_move_line to map it.
I am looking for a domain looking for account_move_line record with accounts like "401.02%" and tagged with the "B:IDN" account_analytic_tag.

**Comment by sbidoul** [comment]
Hi,

Have a look at the examples screenshots in #142.

Do not hesitate to do PR with improvements to the documentation to add such examples.

**Comment by sbidoul** [comment]
Some native support for analytic tags is incoming in #229 and #228
