### ISSUE TITLE
Remove date range from header 

### ISSUE THREAD

**Issue by lili94** [OCA/mis-builder#176]
hi i am using mis builder in odoo V11 i want to remove date range from header and make just the year thanks
![InkedCapture_rep_LI](https://user-images.githubusercontent.com/32308220/56469027-0e22a180-642c-11e9-94d9-cdb07790d022.jpg)

**Comment by elicoidal** [comment]
That could be a good nice to have to have a checkbox for that indeed

**Comment by lili94** [comment]
hi @elicoidal how can i fix it can you explain for me

**Comment by sbidoul** [comment]
There is a [Display Columns Description](https://github.com/OCA/mis-builder/blob/c3d0a2910bdcc3eb00e214745aa80c3797d9c8f1/mis_builder/models/mis_report_instance.py#L452-L454) checkbox that does just that.

This looks like a FAQ, so I think we should rename that checkbox.

**Comment by lili94** [comment]
hi @sbidoul  i download your brunch that have the checkbox field many time but i get this error 
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 1037, in _validate_fields
    check(self)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 342, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 1064, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 519, in raise_view_error
    raise ValueError(message)
ValueError: Le champ `analytic_account_id` n'existe pas
contexte de l'erreur :
Vue `mis.report.instance.view.form`

do i must to doing manually i am using odoo V11 thanks

**Comment by lili94** [comment]
hi @sbidoul can you help me please i am using odoo v11

**Comment by sbidoul** [comment]
@lili94 I suspect this is a problem on your installation. It is working fine on runbot.
Have you run `odoo -u mis_builder` after downloading the latest version?

**Comment by lili94** [comment]
hi @sbidoul i download the mis_builder from here than i add date range and web _widget_color but when i try to install i get this error i will try to run this commande thanks for help

**Comment by lili94** [comment]
thanks it s work thanks so much i will close it
