### ISSUE TITLE
Add Colomun Note to header

### ISSUE THREAD

**Issue by lili94** [OCA/mis-builder#177]
hi in our balance sheet we have colomun Note it is string max 7 caracter i try to add but it doesn't work can you help me (like this ) any idea
![Inkedscreencapture-file-C-Users-Asmaa-AppData-Local-Temp-Instance-MIS-report-QWEB-PDF-report-1-pdf-2019-04-23-10_22_18_LI](https://user-images.githubusercontent.com/32308220/56570616-2f61ca00-65b3-11e9-84df-fd32b57e33fc.jpg)
thanks

**Comment by lili94** [comment]
@sbidoul  can anyone help

**Comment by sbidoul** [comment]
@lili94 this is feature does not exist today. This sounds similar to #159.

**Comment by lili94** [comment]
hi  can we start devlop together this features i need it so much next week  thanks
@sbidoul

**Comment by sbidoul** [comment]
I'm closing this one as I don't see a clear path to add a note column. Footnote should cover the use case.

@lili94 if you want to finance the development of footnotes, do not hesitate to contact me.
