### ISSUE TITLE
The Analytic Account filter don't work when exporting to xls

### ISSUE THREAD

**Issue by rafagf1** [OCA/mis-builder#178]
Hello,

I have version 11.0.3.3.0 of "mis_builder".
I am using Analytic Account to filter the reports, the filter is applied correctly in the preview and when generating the pdf, but when exporting to xls the filter don't apply.

Is it a bug? Do I need to configure something else?

Thanks

**Comment by sbidoul** [comment]
This would be a bug. But I more or less remember having tested that manually myself and it worked.

Can you try reproducing the problem on runbot and provide detailed steps?

**Comment by rafagf1** [comment]
I have seen that the "generate_xlsx_report" method of module don't have the filter available in context.

Modifying the context within the method:

context = dict (objects._context_with_filters ())
objects = objects.with_context (context)

It work.

**Comment by rafagf1** [comment]
In https://runbot.odoo-community.org/runbot/248/11.0
there is a report created "informe 2" that has an analytical accounting filter, if we see the "preview" it shows correctly "$ 4,999.99", but if we export it shows "$ 14999.99" which is the total figure without applying the filter.

**Comment by sbidoul** [comment]
Thanks for the detailed report. I'll look into it as soon as possible.

**Comment by sbidoul** [comment]
I suspect this bug is for 11 and 12 only.

**Comment by sbidoul** [comment]
I think we need this patch: https://github.com/OCA/reporting-engine/pull/259

**Comment by sbidoul** [comment]
Part of the fix is in #182, the other part is proposed in https://github.com/OCA/reporting-engine/pull/259#issuecomment-487680036

**Comment by sbidoul** [comment]
This should be resolved now. Let me know if not.
