### ISSUE TITLE
Can't see the MIS Reporting sub menu after install mis-builder

### ISSUE THREAD

**Issue by hitrosol** [OCA/mis-builder#181]
I have installed the mis-builder on odoo 12, but can't see the submenu in Accounting -> Configuration.

Previously, I have installed the Odoo12 Accounting By Odoo Mates, Odoo SA.

**Comment by sbidoul** [comment]
I don't know that Odoo 12 Accounting module, but I suspect it's doing things with the menus so it's probably the cause of the problem.

Can you try installing MIS Builder on a fresh database, see if you can find the MIS menus, and then only adding that module?

**Comment by hitrosol** [comment]
I have reinstalled the MIS Builder addons from fresh database also install the Odoo 12 Accounting module, it's working well. Hopefully, there will be much references how to use this module.
Thanks.
