### ISSUE TITLE
learn to design kpi and query

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/mis-builder#184]
I have problems in designing a report with accounts and analytical accounts. 
Can someone recommend me a link or book to learn KPIs and queries with MisReports?

**Comment by sbidoul** [comment]
There is no book (yet? hehe). 

There is a user documentation at https://oca-mis-builder.readthedocs.io/en/10.0/. It can still be improved and contributions are welcome. The source of the doc is in GitHub at https://github.com/OCA/mis-builder/tree/10.0/docs.

[Issues with label question](https://github.com/OCA/mis-builder/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion) can also be a useful source of information.

**Comment by pepitovadecurt** [comment]
Thanks sbidoul !
I've got what you need with the links. 
Obtain a 18% values that have specific analytic account:
`bale[18%][('analytic_account_id.display_name', '=', 'name_on_analytic_account')]`
disadvantage: the kpi description need to put manually

I use the query more complicated because I can not find any information.

**Comment by sbidoul** [comment]
Queries is indeed an area of the documentation that needs improvement.

**Comment by pahangm** [comment]
> Queries is indeed an area of the documentation that needs improvement.

please...
