### ISSUE TITLE
Can't convert the amount currency to default currency in Commitment Column

### ISSUE THREAD

**Issue by hitrosol** [OCA/mis-builder#188]
I found an inconsistent commitment amount if the purchase order was made in other currency. 

![image](https://user-images.githubusercontent.com/5949936/57194883-5ab2c480-6f76-11e9-8f56-845fd7b3d9c9.png)

I think that's because in the drill down list, the is no amount currency  column in the committed column.

![image](https://user-images.githubusercontent.com/5949936/57194897-8635af00-6f76-11e9-8490-03a7fd95886c.png)

where we can see that column in the actual one :
![image](https://user-images.githubusercontent.com/5949936/57194992-90a47880-6f77-11e9-8bb3-a1899159e651.png)

It would also help if we can put the source document number in the list of commitment and actual.

I test it in the runbot v 12, I can't test in other version since the username and password have changed.

I'm sorry, I haven't have the skill to contribute on fixing the module, but I can allocate my time to test it so it will be ready for the community.

**Comment by sbidoul** [comment]
This view is part of `mis_builder_demo`, which is only a demo, not suitable for production use. There is a [warning about it in the code](https://github.com/OCA/mis-builder/blob/8a70a2607dce54d608e83ecb8f68c4f4f9094219/mis_builder_demo/models/mis_committed_purchase.sql#L4).

**Comment by hitrosol** [comment]
noted
