### ISSUE TITLE
consolidation report with different base currency

### ISSUE THREAD

**Issue by hitrosol** [OCA/mis-builder#189]
For consolidation in multi company report with different base currency, has this module consider the [IAS 21 The Effects of Changes in Foreign Exchange Rates ?](https://www.ifrs.org/issued-standards/list-of-standards/ias-21-the-effects-of-changes-in-foreign-exchange-rates/).

**Comment by sbidoul** [comment]
IIRC all currency conversions are done using the date of the end of the reporting period.

**Comment by hitrosol** [comment]
The reason I asked this because according to the standard, we have to make sure that P&L accounts are consolidated using monthly rates and B.S accounts using standard 'spot' rates of parent company.
In the other words, P&L accounts should be translated to base currency of the parent company in the historical rate.
In Odoo and this addons, I did brief check, and all the accounts are translated using the date rate report.

Meanwhile, I found addon that concern about this issue : 
https://apps.odoo.com/apps/modules/11.0/account_consolidation/

**Comment by fclementic2c** [comment]
Yes, I totally agree @hitrosol.
P&L account must be converted at average rate and BS account at month end rate.
You must have 2 tables to log xrate : for std and an other one for average rates -> see: https://github.com/OCA/currency/tree/11.0/currency_monthly_rate.

Then the currency rate difference you get must go in a P&L account.

see my doc about the https://apps.odoo.com/apps/modules/11.0/account_consolidation/
[BS-Accoutingconsolidation-080519-1733-4.pdf](https://github.com/OCA/mis-builder/files/3158105/BS-Accoutingconsolidation-080519-1733-4.pdf)

**Comment by sbidoul** [comment]
I'm not disagreeing either ;) PR welcome.

**Comment by sbidoul** [comment]
Note however that if you do that naively, a consolidated trial balance will not be balanced anymore. So there is food for thought there.

**Comment by fclementic2c** [comment]
Well Account_consolidation + MIS is already a working solution.
... but maybe the goal is to ask MIS to do the job of MIS conso on the fly

**Comment by hitrosol** [comment]
Thanks all for the same understanding about this. I also agree that the consolidation will be done on the fly, i think no need further journal entries should be created for this consolidation effort. I see ERPNext is quite advance to provide the similar feature. Regards.
