### ISSUE TITLE
KPI description from value

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/mis-builder#197]
Hi, is posible to get the KPI description from (for example) analytic account name?

**Comment by sbidoul** [comment]
Hi, I don't understand your question. Can you elaborate, with an example of your use case?

**Comment by pepitovadecurt** [comment]
Need to put the "Analytic account name" in the description, like this:
![imagen](https://user-images.githubusercontent.com/42767320/58014214-9ada8100-7af8-11e9-87ea-2734d0998659.png)

**Comment by sbidoul** [comment]
That is not supported, the KPI description are not computed.
There is a rough idea to implement automatic expansion by analytic account but it is a hard problem.
It is tracked in #115

**Comment by sbidoul** [comment]
#149 might be a possibility too.

**Comment by pepitovadecurt** [comment]
Thanks sbidoul, I'll try but seems complicated.

**Comment by sbidoul** [comment]
> I'll try but seems complicated.

It seems complicated because it is indeed complicated :) This module is not designed for that at the moment. I'll keep this ticked closed because it is tracked elsewhere.

**Comment by lili94** [comment]
hi @pepitovadecurt  do you have any idea how to make tow column with different expression please
