### ISSUE TITLE
Cannot use date_to or date_from in expression?

### ISSUE THREAD

**Issue by erick-tejada** [OCA/mis-builder#200]
I am writing expressions such as this:

bal[4%][('date', '<', date_from)]
bal[4%][('date', '>=', date_to)]
bal[4%][('date', '<', '%s-01-01' % date_from.year)]

But I always get a Not Defined error:

> ValueError: <class 'NameError'>: "name 'date_from' is not defined" while evaluating
"[('date', '<', date_from)]"

Am I using date_to/date_from wrong or Am I missing something? I have tried this is versions 9.0 and12.0.

**Comment by sbidoul** [comment]
This is not supported and should not be necessary as the date filters are implicit.

Year to date support is being worked on and is tracked in #165.
