### ISSUE TITLE
How to make tow colomn with different expression

### ISSUE THREAD

**Issue by lili94** [OCA/mis-builder#202]
Hi,I want to make to column with same expression and  different  expression  ( different account )
![IMG_20190529_080818](https://user-images.githubusercontent.com/32308220/58542410-787ded00-81f5-11e9-9697-f1c288b5ee0d.jpg) for 2019 I make it normally, 2019 AMORT+PROV I don't know how 2019 Nets is addition of tow colomn please help
![Uploading IMG_20190529_080818.jpg…]()

**Comment by lili94** [comment]
hi @sbidoul please i need help

**Comment by lili94** [comment]
@pedrobaeza can you help me please?

**Comment by pedrobaeza** [comment]
That's not possible right now. See #156 for a possible solution.
