### ISSUE TITLE
how to make counter party in mis builder

### ISSUE THREAD

**Issue by lili94** [OCA/mis-builder#204]
hi i want to implement cash flow statement and i need to make counter-party can we do it in mis-builder please

**Comment by sbidoul** [comment]
Sorry, I don't understand the question.

**Comment by lili94** [comment]
In cash flow statement we need to chose for exemple sum only account start with 41and passed with account 52 (bank) ,how can do something like this in mis builder please

**Comment by sbidoul** [comment]
Ah I see, for that you typically filter on the bank journal. Something like this:

`balp[41%][('journal_id.code', '=', 'BNK1')]`

**Comment by lili94** [comment]
thanks @sbidoul  your methode work for all my report just 1 line when i must to use tow journal for exmple i have balp[158%,42%,625%] that passed with (52 and 53) (journal bank, and journal cash)not in same journal please
 i try this doesn't work 
`-balp[158%,42%,625%,631%,638%,276%,409900%,411%][('journal_id.code', '=', '4') ,'&',('journal_id.code', '=', '5')] `

@sbidoul @pedrobaeza

**Comment by lili94** [comment]
Hi do you have any idea how to do it please

**Comment by lili94** [comment]
i fix it like this 
-balp[401%,403%,622%,408%,60%,61%,65%,3%,467%,476%,487%,623%,628%,77%,4090%,4095%,45%,486%,581%,624%,626%,621%][('journal_id.code', '=', '4')] -balp[622%,60%,61%,65%,3%,581%,626%][('journal_id.code', '=', '5')]
thanks

**Comment by sbidoul** [comment]
Thanks for reporting your solution.
