### ISSUE TITLE
How to call to another expression in a colomun of other report

### ISSUE THREAD

**Issue by lili94** [OCA/mis-builder#205]
Hi  i have questions 
i make report of activ balance sheet i have 2 colomun with different expression for exemple 1st  kpi : 

encaissements reçu de client ->column1          -> column 2
                                               ->balp[41%]        ->bali[60%]
How to make it please can we use call from other report for this second column

**Comment by lili94** [comment]
@sbidoul do you have any suggest please?

**Comment by sbidoul** [comment]
I don't understand the question

**Comment by lili94** [comment]
hi @sbidoul thanks, in my report i have to colomun : (each one have same description and different expression)
Description    |        2019(brut)   |    2019(Amort)
1                     |       balp[40%]     |  balp[60%]

can we do somthing like this in mis_builder@sbidoul

**Comment by lili94** [comment]
@sbidoul any suggest please?

**Comment by sbidoul** [comment]
Have you looked at subkpis?

**Comment by lili94** [comment]
@sbidoul yes, and i try it but i didn't know how to call in second colomun for the same description , i always get error

**Comment by lili94** [comment]
can you give me an exemple please @sbidoul

**Comment by lili94** [comment]
thanks @sbidoul  i resolve the problem with subkpi , thanks so much 
i create subkpi  and in expression chose Multi for each one write your expression 
![bilan](https://user-images.githubusercontent.com/32308220/61181047-6ecf0e00-a618-11e9-8373-95c373e32b5c.PNG)
 but i have one issue when the description is none i gut an error
