### ISSUE TITLE
how to use subkpi  in the  same description

### ISSUE THREAD

**Issue by lili94** [OCA/mis-builder#212]
hi in my report  i  have a description for exmple : **good will** that have tow colomn 
1- **Net**  and 2 **Brut** source **float** with diffirent expression 
 for exemple : 

> good will -> in Net -> balp[70%] and
>  good will-> in Brut -> balp[60%]  

    same line 

how can resolve somthing like this please @sbidoul @pedrobaeza

**Comment by sbidoul** [comment]
To have different expressions on the same line, the only solution is subkpis. If it does not work for you, consider making two lines.

**Comment by lili94** [comment]
i didn't know how to use it can you give me just an exemple please
