### ISSUE TITLE
error after last merge

### ISSUE THREAD

**Issue by lili94** [OCA/mis-builder#216]
hi when i try to install last download i got this`File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 1041, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Erreur lors de la validation de la contrainte

Comment not terminated, line 378, column 93
None" while parsing None:12, near
<data inherit_id="web.report_assets_common">
        <xpath expr="." position="inside">
          <link href="/mis_builder/static/src/css/report.css" rel="stylesheet"/>
        </xpath>
    </data>`
thanks to help

**Comment by sbidoul** [comment]
v11 installs correctly in travis and runbot.

Please double check your setup, and if the problem persists provide a detailed stack traces and instructions to reproduce the issue.

**Comment by lili94** [comment]
everything work perfect thanks
