### ISSUE TITLE
Budget commitment, i.e., PR (commit) -> PO (commit) -> Invoice (actual)

### ISSUE THREAD

**Issue by kittiu** [OCA/mis-builder#217]
Hello @sbidoul @jbeficent 
cc @wipawii

First of all, I am new to these modules. But I did looking into both account_move_budget and mis_builder_budget. If I am not wrong, the objective of both are into reporting purposes by comparing the Actual (from move lines) VS Budget Amount. These are all working well by the modules.

I am wondering if you have been looking into use case where we need to track the PR/PO budget as commitment too?

For example, i.e., a project budgeted at 1,000 USD
- PR at 300, this make,
  - PR Committed = 300, PO Committed = 0, Invoice Actual = 0, Budget Balance = 700
- Partial PR -> PO at 200
  - PR Committed = 100, PO Committed = 200, Invoice Actual = 0, Budget Balance = 700
- PO -> Invoice at 200, also and new PR at 50
  - PR Committed = 150, PO Committed = 0, Invoice Actual = 200, Budget Balance = 650

And also, once the Budget Balance is less, to also mechanism to Block or Warn user when PR/PO/Invoice makes Budget Balance < 0.0

Then, we can create some kind of budget monitoring report, that show all, pr commit, po commit, inv actual, consumed (pr+po+inv) and balance (budget-consumed)

Thank you!

PS: I though I have seen it somewhere about transfer budget commitment between document, but couldn't find it...

**Comment by sbidoul** [comment]
> First of all, I am new to these modules

Welcome :)

> Then, we can create some kind of budget monitoring report, that show all, pr commit, po commit, inv actual, consumed (pr+po+inv) and balance (budget-consumed)

Have a look at `mis_builder_demo` which shows an example of how to do this (with PO onlys, no PR).
A high level explanation on how it works is in my Odoo Experience 2017 talk (the video is linked in the repo README).

It's a demo module only because in my experience, the exact definition of what a budget commitment is is highly variable from one company to another.

> transfer budget commitment between document

That is another possible approach indeed: instead of having a SQL view on unvoiced PO/PR, one can imagine a kind of budget/commitment accounting. I'm not aware of any module that does that.

**Comment by kittiu** [comment]
Thank you @sbidoul for pointing to where I left forgotten. Ya, I think I should have read it from your slide :)

I think you understand my point very well, as you mentioned `one can imagine a kind of budget/commitment accounting`.

That's what we did previously (v8), because of the requirement which want the SAP like feature, tracebility, costcenter, budget plan, budget check, we end up with a lot of development (which I don't like).

We did make PR/PO/EX and SO to create commit line (account.analytic.line, type=pr_commit, po_commit, etc..), commitment transition in granular level (i.e., partially). Meaning next document create new commit line, the prev document will also create counter negative commit line.
https://github.com/pabi2/pb2_addons/blob/master/account_budget_activity/models/budget_transition.py

And reason `budget/commitment accounting` is required as we need it to do active budget check/block.

Please allow me to discuss out loud. I do like what mis_builder has done. But it is not using the same method in getting the commitment vs actuals, and so it won't be single fact. And as report is not something persistent, we can not use it to actively check/block budget, right?

I am looking into create this kind of budget transition solution, at the same time, want to make it elegant like mis_builder or even being extension out of it.

Is it something you would ever need? Anything I missed that you want to remarks?

**Comment by sbidoul** [comment]
@kittiu regarding the check/blocking of PO against available budget, we usually do it with MIS Builder, by flagging a column in a mis report instance as the one that needs to be checked, and then using method `get_kpis_by_account_id()` to find the kpi that is relevant for the PO line, then the `evaluate()` method to find the available amount for that KPI.

Regarding a budget accounting system, you can do it as an extension of mis_builder_budget, or as a separate system. As long as you can provide views that work as alternative sources for mis builder (like mis_builder_demo or account_move_budget do) it will work with mis buidler for display and calculation.

**Comment by pedrobaeza** [comment]
@kittiu check also #154. My idea is to use that as base for creating extension modules for each of the possible future incoming/expenses, creating entries in that table. For example, contract module generates entries for next year, and when the invoice is generated, that entry is removed or reversed (to see what is more interesting). The same can be done for sales, or for purchase (with reverse sign).

Maybe this can be serve also for your purpose.

**Comment by kittiu** [comment]
Great! That make all sense to me. Thanks you very much!

**Comment by kittiu** [comment]
@sbidoul 
Currently, I am working on (similar to what @pedrobaeza mentioned), making new alternate source `budget.commit`, now for purchase commit (and reversed sign when it become actual in invoice confirmed).
![image](https://user-images.githubusercontent.com/1973598/62413870-878e7a80-b63e-11e9-91ff-211ba5934326.png)

- Have you ever doine plan/check budget by the combination of Cost Center (i.e., analytic account) and Account Code?
- As you mentioned `by flagging a column in a mis report instance as the one that needs to be checked...`, you mean the flag is already available or I will need to implement it?

Like governmental budgeting, given an organization with organization chart (i.e., BU > Dept > Costcenter), my goal is to being flexible to set budget by Dept, use budget by Costcenter and lock budget by BU. Then the report is able to show commitment, actual, balance, sum up in any level of org chart + account code.

Actually, about org's chart fields is another topic that I can't find solution by using Odoo's analytic. But I will just focus on analytic for now.

Sorry if the question sound diverged from the intention of mis_builder. But I would think it I could make it fit into the great mis_builder, it will be awesome!

**Comment by sbidoul** [comment]
Hi @kittiu,

> Have you ever doine plan/check budget by the combination of Cost Center (i.e., analytic account) and Account Code?

Yes, using analytic account field on move lines and budget lines (and additional fields for other analytic dimensions). The filtering is done [here](https://github.com/OCA/mis-builder/blob/82a429ead148dff604ab58117d159af9e18a8488/mis_builder/models/mis_report_instance.py#L306-L336).

> by flagging a column in a mis report instance as the one that needs to be checked..., you mean the flag is already available or I will need to implement it?

It is not available out of the box, you need to implement it.
