### ISSUE TITLE
[12.0][ADD] budgeting related features/addons

### ISSUE THREAD

**Issue by kittiu** [OCA/mis-builder#221]
To answer following goal in budgeting related feature with mis_builder, I would like to try adding modules and gathering some feedback.

**Goals**
1. **Budget Commitment:** PR/PO/EX and SO to have accounting budget commitment. I.e., PR-PO-INV, budget will commit when document is confirmed, and reversed commit when passed to next document.
2. **Budget Control:** Ability to lock document when the commit/actual of any document will result in budget balance < 0.0
3. **Budget Chartfield:** Chartfield means, Costcenter/Project, which is analytic_account in Odoo. We want extend 1 and 2 to allowing operate at Costcenter/Project level.
4. **Budget Planning:** As a new budget planning document, for a user in a costcenter to easily fill in a fiscal year budget for his/her business unit. And once confirmed, system to auto create mis report instances as we know about in order to control budget as refer to 1, 2, 3.

**Goal 1: Budget Commitment**

This one can be quite easy, by adding a new table to log all the commitment, i.e., budget.commit. I am looking into create followings addons one for each type of document.
- [ ] purchase_budget_commit
- [ ] expense_budget_commit
- [ ] purchase_request_budget_commit

**Goal 2: Budget Control**

This part will deal with calling available mis_builder's API to find out available budget, and give warning.
- [ ] invoice_budget_control -- I.e., allow user to set to control on invoice, and lock budget on validate invoice.
- [ ] purchase_budget_control
- [ ] expense_budget_control
- [ ] purchase_request_budget_control

**Goal 3: Budget Chartfield:**

TBD

**Goal 4: Budget Planning:**

TBD

**Comment by sbidoul** [comment]
Hi @kittiu, I would suggest to move this discussion to https://github.com/oca/account-budgeting.

**Comment by kittiu** [comment]
moved https://github.com/OCA/account-budgeting/issues/27
