### ISSUE TITLE
[11.0] Cannot update mis_builder if mis_budget_item are present

### ISSUE THREAD

**Issue by enricostano** [OCA/mis-builder#226]
### Versions
```
odoo = 11.0
mis_builder = 11.0.3.4.0
mis_builder_budget = 11.0.3.3.0
l10n_es_mis_report = 11.0.2.2.0
```
### Steps to reproduce
1. Create a MIS budget using "Pérdidas y ganancias abreviado (PGCE 2008)" template
2. Add a `mis_budget_item` to the budget using for example KPI `es40200`
3. Go to Applications > MIS Builder
4. Clic on Update (same if done using Odoo CLI)
5. The following error appears: https://gist.github.com/enricostano/3c564ac745a5dd1aa3099afd8fcb7719
6. Go to the budget
7. Remove all the `mis_budget_item`
8. Clic on Update
9. It works

### Question
Is this the expected behavior?

**Comment by sbidoul** [comment]
This is weird. This happens when the inverse method tries to unlink unused expressions for that kpi. Could it be the previous version of that report template had subkpis? At first glance I would say it is an issue with that particular l10n_es_mis_report, but I'm not sure.

**Comment by enricostano** [comment]
Hi @sbidoul and thanks for your time! I opened an issue in `l10n_es_mis_report` since I'm quite new to MIS reports: https://github.com/OCA/l10n-spain/issues/1185

In any case, I can reproduce this issue on a fresh install.

**Comment by pedrobaeza** [comment]
@sbidoul we are not using subkpis on `l10n_es_mis_report`

**Comment by enricostano** [comment]
I've not seen this issue since we switched to v12. Thanks in any case!
