### ISSUE TITLE
[11.0] Error displaying MIS reports when using MIS budget on same template

### ISSUE THREAD

**Issue by enricostano** [OCA/mis-builder#227]
### Versions
```
odoo = 11.0
mis_builder = 11.0.3.4.0
mis_builder_budget = 11.0.3.3.0
l10n_es_mis_report = 11.0.2.2.0
```
### Steps to reproduce
1. Create a MIS report using "Pérdidas y ganancias abreviado (PGCE 2008)" template
2. Clic on :mag: (preview)
3. It works as expected
4. Create a MIS budget using "Pérdidas y ganancias abreviado (PGCE 2008)" template
5. Add a `mis_budget_item` to the budget using KPI `es40200`
6. Go back to the MIS report and clic on :mag: 
7. It works as expected
8. Go back to the MIS budget
9. Add another `mis_budget_item` to the budget but using KPI `es40100` this time
10. Go to the MIS report and clic on :mag: 
11. The following error appears: https://gist.github.com/enricostano/831ab8a35f5de073cb1a6a5a9fa3d3ff

### Question
Why using KPI `es40100` in a MIS budget breaks the MIS report preview while using `es40200` doesn't?

### Workaround
For some reason, if you update the `mis_builder` module for the Applications section the reports previews will work again... BUT in order to do that you first have to delete all the `mis_budget_item` from the MIS budget or `mis_builder` will not upgrade. This is how I found out this other issue: https://github.com/OCA/mis-builder/issues/226

**Comment by enricostano** [comment]
Any idea on how to solve this? Anyone?

**Comment by sbidoul** [comment]
I just tried to reproduce and could not succeed. I used the latest version of all modules, latest Odoo 11 branch and a fresh database with demo data and `l10n_es`.

```
odoo11-addon-date-range         11.0.2.0.1.99.dev16 
odoo11-addon-l10n-es-mis-report 11.0.2.2.0.99.dev4  
odoo11-addon-mis-builder        11.0.3.5.0.99.dev1  
odoo11-addon-mis-builder-budget 11.0.3.4.0.99.dev1  
odoo11-addon-report-xlsx        11.0.1.0.6          
odoo11-addon-web-widget-color   11.0.1.0.0.99.dev6  
```

![image](https://user-images.githubusercontent.com/692075/70569004-5c420c00-1b99-11ea-9a09-123d0889681b.png)

`odoo -u mis_builder` works fine too.

**Comment by enricostano** [comment]
Closing for now as I've not seen this issue again. Thanks for the help anyway!
