### ISSUE TITLE
Error with adding analytic account in budget in v10

### ISSUE THREAD

**Issue by djulien19** [OCA/mis-builder#238]
Hey,

I'm trying to add analytic account on an existing budget line item .
From the MIS report, I clicked on the details of the amount, and get the budget line item. I selected the analytic account, and when I save, I get:

```
    cr.execute(query, params + (sub_ids,))
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
OperationalError: cannot update view "mis_committed_purchase"
DETAIL:  Views that return window functions are not automatically updatable.
HINT:  To enable updating the view, provide an INSTEAD OF UPDATE trigger or an unconditional ON UPDATE DO INSTEAD rule.
```

**Comment by djulien19** [comment]
http://3388792-237-f234a0.runbot1.odoo-community.org/web#id=1&view_type=form&model=mis.committed.purchase

**Comment by sbidoul** [comment]
@djulien19 according to the error message, it seems you clicked on an item of the "Commitment" column. These items cannot be changed from there, because it's actually a view on other objects (such as invoice line or purchase order lines).

**Comment by sbidoul** [comment]
@djulien19 is this still an issue?

**Comment by sbidoul** [comment]
Closing without feedback from OP.
