### ISSUE TITLE
Move items in KPI to different page

### ISSUE THREAD

**Issue by hitrosol** [OCA/mis-builder#239]
Hi all,

I have created KPIs in the MIS Report Templates. 
![image](https://user-images.githubusercontent.com/5949936/66612796-b48a7b00-ebf5-11e9-9f7d-057a7f3cc71a.png)

It seems 1 page only cover 40 items maximum. I have difficulty to move the item in the second page to first page. 
Other option, maybe I can increase the limit of items per page.
Anyone can help how to do this ?

Thanks,

**Comment by sbidoul** [comment]
Could you make it work?

**Comment by hitrosol** [comment]
I do manually, by changing the latest item information in to the section i want then add the new one in the next page to replace the one I changed. Temporary this solution is fine, if I want to add one or to item in the middle, but it will be complicated if I have to insert some new items in the middle. 
Hopefully there will be more easier solution for this.

**Comment by hitrosol** [comment]
I just realized that the counter record can be adjusted to show all the record in one page....  now It much easier to revise the report template...

![image](https://user-images.githubusercontent.com/5949936/87246010-749e4000-c474-11ea-805a-c7303d4eaadc.png)
