### ISSUE TITLE
Where is mis_builder_budget_assignment?

### ISSUE THREAD

**Issue by kittiu** [OCA/mis-builder#247]
I somehow saw the `mis_builder_budget_assignment` addon somewhere. But now I try to find and couldn't find it in this repo.
Are you familiar with it?

**Comment by sbidoul** [comment]
I don't know about such a module. What would it do?

**Comment by kittiu** [comment]
Oh, sorry. There was a guy what did some extension to mis_budget, and sent it to me. I by chance saw it on my machine today, and was confused.
Sorry, I will close this now.

**Comment by sbidoul** [comment]
I'm still curious about what assignment means in this context :)

**Comment by kittiu** [comment]
For mis.budget.item to have assignee_id. And it goes through approval process. Then, there is a dash board that display how many item is approved :).
Let me know if you want to see it, I can ask from that person and send  you the addon.

**Comment by sbidoul** [comment]
Ah ok, so it's in the area of the budget creation process. Thanks.

**Comment by sbidoul** [comment]
> I can ask from that person and send you

BTW, if you have received the source code and it depends on `mis_builder_budget` you have permission to distribute it - because of AGPL.
