### ISSUE TITLE
Can I have decimals on Percentage on MIS report ?

### ISSUE THREAD

**Issue by fclementic2c** [OCA/mis-builder#251]
I am under odoo 12

Is there a set up or trick to avoid coding ? 

Thanks :)

**Comment by sbidoul** [comment]
Can you elaborate a tiny little bit?

**Comment by fclementic2c** [comment]
I can :)

This is a basic P&L report where I have subtotals lines and the line
underneath shows a % of this subtotal compares to Sales for ex.
see my screenshots below

**Comment by fclementic2c** [comment]
![screenshots](https://user-images.githubusercontent.com/5735158/70928106-9ba4a880-2030-11ea-8c50-a7890ea2806d.png)

**Comment by fclementic2c** [comment]
Ok found ... The rounding field on the style

**Comment by sbidoul** [comment]
Exactly that, yes :)
