### ISSUE TITLE
Date range selector

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/mis-builder#253]
Is there a way to request a date range before a report is generated?
Or is easy to create programming?
Thanks!

**Comment by sbidoul** [comment]
@pepitovadecurt I don't understand your question. Could you elaborate?

**Comment by pepitovadecurt** [comment]
Sorry! 
When call a report need to request date range each time.

**Comment by sbidoul** [comment]
Sorry I still don't understand. MIS Builder reports do specify date ranges and these are preserved each time the report is opened. Maybe you can posts screenshots or a video explaining your issue?
