### ISSUE TITLE
[RFC] Lock templates for avoiding modifications

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/mis-builder#265]
For example, in https://github.com/OCA/l10n-spain/tree/12.0/l10n_es_mis_report, we provide several MIS templates for the reports, and some people edit them for customizing for their companies, but each time the module is updated, the template gets reset (or even worst, can generate an error for example having a related budget item linked to a custom expression).

My proposal is to have an extra field called `locked` or similar (with `copy=False` and `default=False`), not shown in UI, but possible to be set in XML data like the above module, and avoid the modification of that templates.

**Comment by HaraldPanten** [comment]
We haven't had that need yet, but it seems a good new feature.

**Comment by sbidoul** [comment]
Yes I see what you mean. Maybe we don't need an additional field, since we could inspect the `noupdate` attribute?

A hard locking is perhaps a bit too strong / complex to implement? How about a warning banner if the xmlid of the report template has `noupdate=0`? Could that even become a generic module?

**Comment by pedrobaeza** [comment]
Well, I think this is not only something that comes from noupdate=0 records in third modules, but something that can fit into other flows. Imagine the following: a general financial manager in a holding company provides general templates (created by hand) for their children companies, but each of the companies require some adaptations. He/she protects the templates and only allow to copy them, or on contrary, that modifications will be spread across all companies.

That way, the field is the most suitable solution IMO. We can include a button only accessible to a special group for locking/unlocking if needed.
