### ISSUE TITLE
[11+] Show foreign currency per account

### ISSUE THREAD

**Issue by harlibeub** [OCA/mis-builder#273]
Hello

how is it possible to show foreign currency (amount_currency) per account line in eg. profit & loss or balance sheet?

i found about queries which can made in different ways, but not a solution.

current if preview of report, we see: code, name and balance
idea is to see: code, name, balance of amount_currency, balance

if i'm on wrong channel, let me know, where to get help or a hint with a example..

many
thx

**Comment by sbidoul** [comment]
Hello, This is currently not supported.
