### ISSUE TITLE
call initial balance using bali over the calendar year

### ISSUE THREAD

**Issue by hitrosol** [OCA/mis-builder#278]
I'm using bali to call the beginning balance over the calendar year. I found that the balance is become zero for transactions over the calendar year, i.e : month of January.  it seems it doesn't cover the multi year calculation ?

**Comment by sbidoul** [comment]
bali/bale accumulate from the beginning of the fiscal year for P&L accounts, and from the beginning of time for BS accounts. 

Does that help? If not feel free to elaborate your question so we can investigate further.

**Comment by sbidoul** [comment]
Closing after almost two months without feedback.
