### ISSUE TITLE
Functional and technical documentation

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#28]
Several people have expressed interest for writing functional documentation.

This issue is for coordinating this effort.

Technically, it must be in `.rst` format. 

I propose to create one `docs` directory at the root of the repository.

Ideally, the documentation should be modular, to enable to generate a subset for each module (mis_builder, mis_builder_budget) while keeping the possibility to generate a documentation web site for the whole set.

I'll try to put the documentation framework in place soon. In the meantime do not hesitate to propose what you have, in any format.

**Comment by elicoidal** [comment]
:+1: for the top directory in the repo + rst format (I think this discussion actually should be wider than only MIS Builder)
We need to define templates and scope of the documentation: at least Functional/Technical/tests cases.
Modularity might not  be always possible but that should be the first choice.

**Comment by pedrobaeza** [comment]
I think this can be applied to all OCA projects, so this is a general discussion. Take also into account the multiple versions if published in a website

**Comment by elicoidal** [comment]
@sbidoul have you made progress on this topic?

**Comment by sbidoul** [comment]
Bootstrapped in #79
