### ISSUE TITLE
Analytic Account on MIS

### ISSUE THREAD

**Issue by DEVHSCO** [OCA/mis-builder#290]
Hi Everyone,

We are trying to get a report that includes a list of analitic account, the distribution is as follow (columns):

Analitic Account - Sales (analitic Acccount) - Costs (analitic Account)

But i dont know how to writte the expression in KPI or Querys to get this kind of report. 

on the documentation about MIS Builder doesn't speak about analitic account, so we dont find the answer on that book.

thanks in advance

**Comment by sbidoul** [comment]
MIS Builder is not right tool for this kind of report at this point. It may evolve towards that in the future but there is no concrete plan for that at the moment.
