### ISSUE TITLE
[13.0]  Unnecessary dependency

### ISSUE THREAD

**Issue by AntoniRomera** [OCA/mis-builder#299]
This module depends on 'web_widget_color'  which in version 13.0 is not provided by 'OCA/web', it should be removed

**Comment by sbidoul** [comment]
Are you sure you have the latest version? I don't see that dependency on the 13.0 branch:

https://github.com/OCA/mis-builder/blob/f221f607dbcdd7e8e81f77528d36f2329cb425fc/mis_builder/__manifest__.py#L13-L18

**Comment by AntoniRomera** [comment]
My fault, I had a wrong version, I feel the annoyances
