### ISSUE TITLE
aep.py float_is_zero rounding

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/mis-builder#30]
Are you sure the following:
```
float_is_zero(debit-credit,
precision_rounding=self.dp)
```
is right?
Correct me if I'm wrong but it seems that self.dp which is currency decimal_places is the number of decimals to take, this is an integer like 2 decimals (1.01) and you are passing this in the precision_rounding parameter of float_is_zero.
Shouldn't you use the precision_digits parameters instead?
```
float_is_zero(debit-credit,
precision_digits=self.dp)
```

**Comment by sbidoul** [comment]
Indeed. Well spotted.
