### ISSUE TITLE
Reports apply to all models

### ISSUE THREAD

**Issue by InformaticaArelux** [OCA/mis-builder#303]
I think the mis-builder addon is very powerful and flexible to obtain reports BUT only with respect to move lines and I think that this is a "mistake", that is, I think the addon could be considered as a reporting system at the level of any model.

For example, if we try to make a completely customized sales report, it is not possible, since in the mis.report model, the move_line_sources field only allows me to select move lines.

The changes that occur to me to propose this change with respect to what was previously used would be:

**Model mis_report**
- Change move_line_sources to ir_model (many2one)

**Model mis_report_kpi**
- Change _auto_expand_account_ to _auto_expand_
- Add the _auto_expand_field_id_ field (showing the list of the -ir_field- fields with respect to the model selected in the report and then group the data with respect to this field).

**Model mis_report_instance**
- Delete the _target_move_ field
- Add the _domain_ field (Ex: [('type', '=', 'posted')] to simulate what is currently done regarding the entries entered)

Lastly, I think the addon should be available globally as an item in the Odoo menu.

**Comment by HaraldPanten** [comment]
Hi @OdooNodrizaTech ,

You can use MIS Builder for any other model using queries, for example. You can also try with others like bi_sql_editor, bi_view_editor...

Did you consider any of these options?

**Comment by InformaticaArelux** [comment]
Hi @HaraldPanten 

I did not know it and the truth can solve many things for me.

**Comment by HaraldPanten** [comment]
Sounds good 👍 

I think this issue can be closed, then.
