### ISSUE TITLE
Transifex German: Copy translation of version 9.0 to 10.0 and 11.0

### ISSUE THREAD

**Issue by treviser** [OCA/mis-builder#31]
I have completely translated version 9.0 to german. Could somebody open the translations and copy the translations to the newer versions?

**Comment by pedrobaeza** [comment]
Please do it yourself exporting and importing from Transifex.

**Comment by treviser** [comment]
It did not come to my mind that I just could do that myself without any special access rights :-o
Done!

**Comment by treviser** [comment]
@pedrobaeza The source for 10.0 is empty. But I can't update the source, it seems I do not have the necessary rights.

**Comment by pedrobaeza** [comment]
Are you trying to add more resources?

**Comment by treviser** [comment]
No

**Comment by treviser** [comment]
I tried to manually update the resources like here: https://docs.transifex.com/projects/updating-content

**Comment by treviser** [comment]
@pedrobaeza Should I change the project-id-version in the .po file like so:

"Project-Id-Version: Odoo Server 10.0c\n"

**Comment by Fuchur777** [comment]
@treviser Cannot seem to find your German v10 translations.

I just translated v9 Dutch, would like to get this for 10 to.
And get the file ready for v11.

@pedrobaeza can you shed some light on it for me/us?

**Comment by treviser** [comment]
@Fuchur777 I did translate v9 to German, and @mart-e from Odoo SA seems to know how to copy translations to new branches on the Odoo repositories. But the translation files for v10 are empty, so there is nothing to translate and I do not know who is responsible to create these files and also to forward copy them. The German OCA language coordinator is not reachable and does not react to inquiries. So I'm quite pissed off and highly demotivated.

**Comment by mart-e** [comment]
You can go to Organisation Settings > Translation Memory and select or create one TM that will be shared amongst all projects.

![screenshot-2018-1-5 odoo - translation memory transifex](https://user-images.githubusercontent.com/564822/34616296-228d8ebc-f238-11e7-9852-0b3173a1f96d.png)

Also, be sure to check "Translation Memory Fill-up" in your project Settings > Workflow

I noticed Transifex fails to synchronise from time to time (when adding new languages for instance) so I have to uncheck, save and recheck the "Translation Memory Fill-up" option

**Comment by treviser** [comment]
@mart-e Thank you very much for the help. Now we have only to find somebody who is able/responsible to do that :-)

**Comment by sbidoul** [comment]
@treviser I may have the rights to do that. Let me check.

**Comment by sbidoul** [comment]
@treviser there are no English strings in transifex for mis-builder 10.0 (as you reported above, sorry I did not spot that message). That is weird, I'm investigating.

**Comment by pedrobaeza** [comment]
There was an error in Transifex Travis stage that makes to not work. Rebuild that stage on 10.0 branch to see if they are now filled.

**Comment by sbidoul** [comment]
Thanks Pedro. Build in progress https://travis-ci.org/OCA/mis-builder/jobs/303724125

**Comment by sbidoul** [comment]
@treviser it looks better now. I uploaded the v9 translations in 10 for mis_builder.

So I close this one. Feel free to reopen if there is still anything wrong.

**Comment by treviser** [comment]
@sbidoul Thank you very much!
