### ISSUE TITLE
Reporting on different periods in the same column

### ISSUE THREAD

**Issue by bennals** [OCA/mis-builder#319]
Apologies in advance if asking a usage question is inappropriate for this issues section.

I'm wondering if there is a way to report on a single month (the month preceeding the base date) for one kpi, and then three months preceeding the base date for another kpi, all in the one column.

The reason I ask is that here in Australia we have to submit an report to the tax office every quarter that reports the amount of GST (similar to VAT) paid over the last quarter, but income tax withheld from employees only for the last month.

If it's possible to use different periods in the one column, creating a neat report to satisfy the tax office would be very easy.  I was wondering if it could be achieved with some python code in the KPI expressions for instance, but I don't know enough python to figure it out myself.

Thanks for this extremely useful module by the way.

**Comment by sbidoul** [comment]
@bennals I'm not sure how we could address this use case.

I think there was an idea to pass the period dates from/to in the evaluation context of expressions, but that would certainly requires clarifying the use cases to get it right.

**Comment by mileo** [comment]
Hi,

This is possible, we made some modifications in version 8.0 to make this Brazilian report:

![image](https://user-images.githubusercontent.com/1975978/97162349-da7db180-175d-11eb-9359-0ba88170b403.png)

Please check:

https://github.com/abgfbr/mis-builder
https://github.com/abgfbr/l10n-brazil/blob/develop/l10n_br_contabilidade/models/mis_builder.py
https://github.com/abgfbr/l10n-brazil/blob/develop/l10n_br_contabilidade/models/ <- many other mis builder files

In the future we intend to propose this improvement.

**Comment by c4hinnova** [comment]
Greetings,
Use case: pass the period dates from/to in the evaluation context of expressions subtracting one year to manual_date_from and manual_date_to. what could be the expression?
 
@sbidoul 
@mileo
