### ISSUE TITLE
Show date in print report v.11

### ISSUE THREAD

**Issue by asouma764** [OCA/mis-builder#345]
hi am new in mis_builder and i want to show date in header report after print how can i do this

thanks

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by asouma764** [comment]
hi but when you have 2 year and use o.date_from it deosn't appear
