### ISSUE TITLE
how to use SUBKPI name in second SUBKPI expression existing within the same KPI

### ISSUE THREAD

**Issue by 8-chems** [OCA/mis-builder#348]
Hi, for the example of kpi1 of multi subkpis (subkpi1, and subkpi2), how can I define the expression of subkpi2 as it takes the value: kpi1.subkpi1*0.19 in mis 13?

**Comment by sbidoul** [comment]
You can only reference subkpis from another kpi, not from the same one. If needed you can create a hidden kpi as intermediary value.

**Comment by 8-chems** [comment]
@sbidoul it would be a great feature if added, as sometimes subkpis hold long expressions )), thanks for your reply
