### ISSUE TITLE
MIS reports

### ISSUE THREAD

**Issue by ElenaGarmo** [OCA/mis-builder#351]
Hi to everyone,

I don't know if this is an issue or is just me that I don't know how to do it but here's the thing: I would like to filter the reports created with the MIS Builder module by level. I am using the "Plantillas MIS para informes contables Españoles" available at the OCA but it seems that there's no filter by level available.

Has anyone filtered the reports by level?

Thanks so much in advance!

**Comment by sbidoul** [comment]
Hi, what do you mean with "level" in this context?

**Comment by ElenaGarmo** [comment]
Thank you for your time. In Spain, there are levels of breakdown in the financial reports. So, I was wondering if there's a chance to filter the reports depending on the level of detail you wanted them. Unfortunatelly, I have just found out its not possible.
