### ISSUE TITLE
[14.0] analytic tag filters are broken

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#353]
analytic tag filters are broken in 14.0  (resolve_2many_commands is gone)

Need to add a test to reveal the issue

**Comment by HaraldPanten** [comment]
Hi @sbidoul not sure about what is this issue about.

At the moment, mis reports are not distributed as they could be, using analytic tags. Are you planning to add the feature? Probably it's not the right issue, as you have categorized this issue as a bug and not as a feature.

THX!

**Comment by sbidoul** [comment]
A fix is proposed in #479.
