### ISSUE TITLE
Drilldown action name issue with an alternative data source 

### ISSUE THREAD

**Issue by jprokop1** [OCA/mis-builder#354]
it doesn't work in case of an alternative move line source with filled account_id  (example - analytic account - as in mis-builder-contrib/ mis_builder_analytic) 
account name in {kpi} - {account} - {period} is hardcoded from account.account.display_name

**Comment by sbidoul** [comment]
You may want to check if #350 fixes this.

**Comment by jprokop1** [comment]
yes, it works!
Thanks!
