### ISSUE TITLE
[13.0] Printed report name fails

### ISSUE THREAD

**Issue by marcpp** [OCA/mis-builder#366]
On Odoo13CE mis-builder 13.0.3.7.2 when generate a pdf or xlsx the report name of the print_report_name field does not seem to work

**Comment by marcpp** [comment]
the same thing happens with some other reports, maybe the problem is from Odoo?

**Comment by sbidoul** [comment]
If it happens with other reports you probably have a configuration issue. Can you provide details about the error, such as a stack trace ?

**Comment by marcpp** [comment]
> If it happens with other reports you probably have a configuration issue. Can you provide details about the error, such as a stack trace ?

I don't know how to make a stack trace. I send you some screenshots.

![image](https://user-images.githubusercontent.com/1152763/126513601-4bb65b44-b121-4748-9c66-d5aa33b9be82.png)

![image](https://user-images.githubusercontent.com/1152763/126513323-33c31aaa-30b4-4d78-aa60-23f9a9fd08f2.png)
