### ISSUE TITLE
Configure a "% of Sales" report column

### ISSUE THREAD

**Issue by dreispt** [OCA/mis-builder#370]
Having comparisons with % of sales is usual in financial statements, especially for expense accounts.
I having trouble configuring such a column.
Any suggestions please?

cc @sbidoul 
Thanks

**Comment by sbidoul** [comment]
It's not going to be easy to put that in a column. You'll need to add rows with percentage KPIs (such as `cost_of_sales / revenue`...).

**Comment by c4hinnova** [comment]
Greetings, I am trying to do in a subkpi but I have two problems: 1- I don't know how to format% to that subkpi column and 2- I don't know how to remove that subkpi from columns where it is not relevant.
cc @sbidoul
Gracias
