### ISSUE TITLE
Expand by partner

### ISSUE THREAD

**Issue by AntoniRomera** [OCA/mis-builder#378]
I think a great improvement would be to be able to expand by customer in the same way that you do by account.

**Comment by sbidoul** [comment]
Yep, agreed. Unfortunately it is a very non-trivial change...

**Comment by pedrobaeza** [comment]
This links with #115, as the problem is to have a generic grouping mechanism. I did a PR with a working solution, but not renaming variables leads to a weird code reading, and renaming them provokes a lot of conflicts on any upstream change.
