### ISSUE TITLE
[13.0][14.0] mis_builder : Don't supports concurrent multicompany selection

### ISSUE THREAD

**Issue by carlosdauden** [OCA/mis-builder#379]
This domain prevents the selection of several companies according to the use of concurrent multicompany implemented as of v13:
https://github.com/OCA/mis-builder/blob/bfa6677b57491156cbb8c6d1cc16b972fed01f36/mis_builder/views/mis_report_instance.xml#L175
**Simply change...**
¿Can be removed this domain?

**More ambitious change...**

Given the new scenario, can we consider keeping only one of the fields company (query_company_ids) and remove others (company_id and company_ids)?
https://github.com/OCA/mis-builder/blob/bfa6677b57491156cbb8c6d1cc16b972fed01f36/mis_builder/models/mis_report_instance.py#L590-L596
https://github.com/OCA/mis-builder/blob/bfa6677b57491156cbb8c6d1cc16b972fed01f36/mis_builder/models/mis_report_instance.py#L580-L588

**Comment by sbidoul** [comment]
@carlosdauden can you please test #374 and see if it does what you need ?

**Comment by carlosdauden** [comment]
Improved in https://github.com/OCA/mis-builder/pull/374
