### ISSUE TITLE
MIS budget - small improvements proposition

### ISSUE THREAD

**Issue by fclementic2c** [OCA/mis-builder#380]
Knowing that today columns by default are:
* budget by KPI : KPI, Date range, From, To, Account, analytic account, analytic tags
* budget by account:   Company, account, date range, From, To, Debit, Credit, Analytic account, Analytic tags

I suggest few changes:

* The column 'To' is useless and should be removed since MIS cannot split an amount over a period.
ie: you cannot say Electricity from 01/01 until 31/12 then MIS will calculate 1/12th every month when you display your P&L report by month

* The unicity constraint par period and tag (and maybe other fields?) must be removed. I do not understand the point of it actually.
ie: You cannot create 2 budget lines like Electricity 1000€  per business unit (1 BU = 1 analytic tag) 

* We need a field to add a description/Label on each line to have the opportunity to explain what is budgeted

**Comment by sbidoul** [comment]
Hi @fclementic2c can you do an issue per topic, it's easier to track.

That said, it actually *can* do 1/ so from/to is useful, and there are open PRs for 2 and 3 that should land in mis builder 4.

**Comment by sbidoul** [comment]
Items 2 and 3 are implemented in #384 and #382 respectively.
