### ISSUE TITLE
14.0: unable to add SUM COL at once 

### ISSUE THREAD

**Issue by petrus-v** [OCA/mis-builder#393]
Issue is probably known ? I haven't found any similar referenced...

## Module
``mis_builder``

## Describe the bug

Configuring MIS Report, I'm unable to configure a *Sum columns* without saving the new column first. 

## To Reproduce
**Affected versions**: 14.0

1. connect to runbot and go to the `Demo Expenses vs Budget` MIS Report (Invoicing > Reporting > MIS Reports) 
2. Edit the report in form view and add a new column "Available 2"
3. select "sum columns" source (`sumcol`)
4. when you want to add lines of columns to sun the list of available column is empty

**Expected behavior**
available columns fulfilled while creating the sum column

**Additional context**

To be able to configure that kind of column we have to save the column first as regular column then edit again the report to change as sumcol then available column are listed.

**Comment by alexis-via** [comment]
I confirm this bug.

**Comment by alexis-via** [comment]
Bug https://github.com/OCA/mis-builder/issues/456 seems to be a duplicate of this one.

**Comment by alexis-via** [comment]
The field period_to_sum_id has domain="[('report_instance_id', '=', parent.report_instance_id), ('id', '!=', parent.id)]" defined in the view (there is no domain in the code). If I remove ('report_instance_id', '=', parent.report_instance_id) from the domain, this list is not empty any more.

**Comment by alexis-via** [comment]
Here is the exact scenario:
create the MIS report instance with 2 periods
SAVE
create a 3rd period with source = sumcol => in source_sumcol_ids, you cannot select period_to_sum_id (the list is empty).

Workaround:
create the MIS report instance with 2 periods
SAVE
create a 3rd period with source = sumcol and a name
SAVE
edit the 3rd period and the "source_sumcol_ids" will work without problems, you will be able to select period_to_sum_id

**Comment by sbidoul** [comment]
This was fixed in #457
