### ISSUE TITLE
Module Migration Standard to version 15.0

### ISSUE THREAD

**Issue by ChrisOForgeFlow** [OCA/mis-builder#394]
When I try to make process of migration with this guide

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

With this code:
`git format-patch --keep-subject --stdout origin/15.0..origin/14.0 -- $MODULE | git am -3 --keep`

I got this issue:

![image](https://user-images.githubusercontent.com/94866688/146600303-04ccadcf-046e-4703-801c-5858ddb8279c.png)

Do you know if is necessary to check every commit conflict on migration process?

@ForgeFlow

**Comment by pedrobaeza** [comment]
That's because the commit history has been twisted through several chained merges (and that's why other times I ask not to do merge commits inside PRs). But @sbidoul always changes the usual procedure here (to empty the branch) for getting the branch as it was, and mark modules as installable=False. Stèphane, do you want to do it also this time?

**Comment by sbidoul** [comment]
Yes I'll branch 15.0 off 14.0. But first we need to finish #381 (I welcome additional functional review).

**Comment by sbidoul** [comment]
Regarding the migration of merge commits, I wonder if https://github.com/OCA/maintainer-tools/pull/504 can help.

**Comment by sbidoul** [comment]
For now I deleted the 15.0 branch.

**Comment by sebalix** [comment]
@sbidoul to answer you: `oca-port` ignore merge commits, they are not ported by the tool.

**Comment by pedrobaeza** [comment]
The usual problem rescuing commit histories is when there are several commit with multiple parent. The serialization of the commits provokes that the diff are not applied in the same order as they were really done. And if you make conflict resolution in such merge commits, then party is assured, hehe.
