### ISSUE TITLE
[12.0] Show distributed data if distributed analytic labels are used.

### ISSUE THREAD

**Issue by ValentinVinagre** [OCA/mis-builder#419]
Version: 12 ce
Using the analytical labels with the distribution option we create one that distributes 50% in two analytical accounts.
![Selection_142](https://user-images.githubusercontent.com/22913794/155970989-002f0fe0-4de6-4b64-beb5-a973c385e45c.png)

Create an invoice with this analytic tag.
![Selection_143](https://user-images.githubusercontent.com/22913794/155976872-eafc5917-45ce-4127-bf4b-3e128484a54d.png)

The account move line have the tag.
![Selection_144](https://user-images.githubusercontent.com/22913794/155977041-7f7f3f25-aeb5-4824-9c50-56c14d7cf0e9.png)

And the distribution of analytical notes has been carried out correctly.
![Selection_145](https://user-images.githubusercontent.com/22913794/155977147-2324f972-c697-4e7c-ad10-cfe667da5cce.png)

Now we create a my report indicating that we filter by that analytical label

![Captura de pantalla 2022-02-28 a las 12 42 47](https://user-images.githubusercontent.com/22913794/155977879-a45644a7-b81d-427e-830a-21182da29c1e.png)

when we show the details

![Selection_146](https://user-images.githubusercontent.com/22913794/155977947-e2a92b9e-d3e4-4422-8c56-3c2d9758ffaa.png)

The new Feature:
When filtering by an analytic account it should only show the proration for that account. For example:
In this case, if we filter by the "Administrative" account and see the report, €0.50 should come out instead of €1.00, since it is the proportional part of that account.

Possible solution:

We had thought that we could make a separate view-type model that distributes the analytic labels. That is, if for example we have an accounting entry that goes with a distribution of 2 analytical accounts, this view would have to separate that entry into 2 as if they were the cost entries.
This new model would be chosen in the "Move lines source" of the MIS templates.

Do you think this could be a good solution? Or do you suggest a better one?

**Comment by ValentinVinagre** [comment]
@sbidoul @pedrobaeza @HaraldPanten

**Comment by HaraldPanten** [comment]
I think that your purpose is interesting, but maybe we need a more technical point of view, like the one that could be suggested by Pedro or Stéphane.

**Comment by pedrobaeza** [comment]
See `mis_builder_analytic` PR for having an extra data source (with "Real data (alternative)" or so name), and query analytic lines. At account level that can't be done easily.

**Comment by sbidoul** [comment]
Yes, I'd look at mis_builder_analytic too for this kind of stuff. Recomputing the distribution on the fly sound hard to implement efficiently.

**Comment by ValentinVinagre** [comment]
The best 😃 , I have created a pr to add some changes
https://github.com/OCA/mis-builder-contrib/pull/20
