### ISSUE TITLE
[14.0] issue with source type "Sum Columns" in mis reports

### ISSUE THREAD

**Issue by tv-openbig** [OCA/mis-builder#430]
If i want to add another column in mis reports in order to sum up two existing columns i select the source "Sum columns".
This opens a widget on the right side in order to select the columns you want to calculate.

In this widget i click on "Add a line" in order to select at first the sign (+/ -) and then a existing column.
Even if there are existing columns already the list is empty.

I have checked the same on odoo v13. Here it works fine.

## Module
mis_builder

## Describe the bug
I cannot select an existing column if i want to use the source type "Sum columns"

## To Reproduce

Video:
https://drive.google.com/file/d/1_j6XOLW4tlBlHqzFv20JYfdbI2PhmgTk/view

**Expected behavior**
As in v13 and prior versions i should be able to select existing columns in order to use the source type "Sum columns" properly.

**Additional context**
I have tested here: 
https://runboat.odoo-community.org/builds?repo=oca/mis-builder
&target_branch=14.0   == > NOT OK

https://runboat.odoo-community.org/builds?repo=oca/mis-builder
&target_branch=13.0  ==> OK

**Comment by hitrosol** [comment]
Usually, first I will create the **comparison column**, input the **Label** and select the source as a **Sum Columns** then **save** the report without add line in the Sign and Column. 
Then you can edit the Report again, edit the **comparison column** and edit the Sign and Column. 
The field will be shown there.

I know this is not practice but it works at the moment.

**Comment by tv-openbig** [comment]
> 

@hitrosol Thanks, i have checked this. Finally i will close the issue, even if obviously the usability in v13 was a little bit better.
Please compare also my video:
https://drive.google.com/file/d/1eKY9_xiIEH0sVl4fcr-Pfo_I7miB-b7X/view
