### ISSUE TITLE
[15] Cannot add a comparison column like Actual - Commited

### ISSUE THREAD

**Issue by fclementic2c** [OCA/mis-builder#456]
same context that on https://github.com/OCA/mis-builder/issues/455

same document to reproduce : https://docs.google.com/document/d/1dvTCCX51I9ZrgTEvpoFB8AVjLVlie8P5LpxaeUp3PQc/edit?usp=sharing

Just see at the bottom of the doc the bug 2

Thanks

**Comment by alexis-via** [comment]
@fclementic2c I fixed your bug in this PR https://github.com/OCA/mis-builder/pull/457  It's for v14, but you can easily up-port it to v15.

**Comment by sbidoul** [comment]
This was fixed in #474.
