### ISSUE TITLE
MIS budget: Invalid field 'user_type_id.include_initial_balance' in leaf

### ISSUE THREAD

**Issue by kristian-vkd** [OCA/mis-builder#467]
## Module
mis_builder_budget

## Describe the bug
leaf error when comparing with: MIS budget (by accounts).

## To Reproduce
Odoo v12.0
Module version: 12.0.3.5.0

1. Create a MIS budget (by accounts).
- Only necessary to create one budget item 
2. Create a MIS Report template
- Only necessary to create one KPI based on the same account on budget.
3. Create a MIS report instance with the report template just created.
- In the "Columns" tab, add the MIS budget (by accounts), that you just created.
4. Click on the "Preview" or "Print" button.

When previewing or printing, the error occurs.

**Expected behavior**
When clicking on the preview button, the expected behavior is that the report gets rendered, and shown as normal.

**Additional context**
ValueError: Invalid field 'user_type_id.include_initial_balance' in leaf "<osv.ExtendedLeaf: ('user_type_id.include_initial_balance', '=', True) on mis_budget_by_account_item (ctx: )>"

**Comment by davidwul** [comment]
We have the same issue in v14, as soon as you have a budget to compare, if you filter the move line with a field that is not present in the budget line model, you have this error. 
I would add the 14.0 label
Any idea on how to clean this issue?

**Comment by kristian-vkd** [comment]
@davidwul 
In v12 i found a fix that seams to working fine for me.
Just create another module, and depend on the mis_builder_budget

```
class MisBudgetByAccountItem(models.Model):
    _inherit = "mis.budget.by.account.item"

    user_type_id = fields.Many2one('account.account.type', related='account_id.user_type_id', store=True, readonly=True)
```

**Comment by davidwul** [comment]
@kristian-vkd 
thanks, we did that, but it's a pretty dirty workarround. It should work like that. If the field is not available on the budget line, it should be ignored in the domain. It seems weird to add each field via inheritance to make the report "work" no?

**Comment by kristian-vkd** [comment]
@davidwul 
I would not say that the fix is a dirty workaround, because if you want to fix the domain, it will be so much more dyrtier code.
The reason for inheriting, is that I do not make any adjustments directly into modules, because we then will lose ability to get future updates.

Also by making a related field, the data will be transferred from the account type model, and this way we make the "mis.budget.by.account.item" look more like the "account.account" model. and that pleases the domain.

So if OCA does not find a better way to fix this issue, I would say that if they add the field line to the module, it will be a easy fix, and still preserving there domain filter without needing to make any changes to it.

**Comment by sbidoul** [comment]
Hi,

Thanks for reporting this. 

I consider this is a bug, and I welcome a PR to add `user_type_id` to `mis.budget.by.account.item`.

**Comment by sbidoul** [comment]
Or better, a backport to 12.0 of https://github.com/OCA/mis-builder/commit/c3d90afb6757dda381ed6936272767da9d442ffb which is already in 13.0.

**Comment by kristian-vkd** [comment]
Hi @sbidoul 

That could also do the job.

Can you also look on v14, @davidwul reported that he have a similar / same issue on v14?

**Comment by sbidoul** [comment]
In v14 it's likely a different issue. Please open another with a reproducer.

**Comment by davidwul** [comment]
Thanks @sbidoul 
I have created an issue #486
