### ISSUE TITLE
[14.0] MIS Budget: Invalid field account.move.line.payment_state in leaf ('payment_state', '=', 'paid')

### ISSUE THREAD

**Issue by davidwul** [OCA/mis-builder#486]
When filtering the move (actual serie), if we add a comparison column with budget, rendering the report faild. Even if the filed is not budgetable. This fails if the budget lines model does not hold the field filtered on the actual lines. (could be journal_id, state, journal_id, payment_state, etc.)

## Module
mis_builder_budget

## To Reproduce
14.0

1. create a report with a KPI that is filtered on a field not present in the budget line model (e.g. debp[55%][('journal_id.code', '=', 'BNK1')] )
2. add budget and budget line
3. preview the report

**Comment by sbidoul** [comment]
If you are using mis budgets by account, then this is not a bug.
Indeed, I don't think we can realistically add all account.move.line fields to budget items.
If you need budgeting on reports with such filters, you should consider mis budgets by kpis.

**Comment by davidwul** [comment]
Yes, I understand that it makes no sens to add all fields present on move.line on budget lines. I was expecting if the field is not on budget line that it would be ignored. But that might be not realistic or too complicated. (I'm not a dev per se)
But at least, if the kpi is not budgetable the error should not occurs. I would consider this as a bug in that case.
