### ISSUE TITLE
Add **Undefined** to Analtyic Account Filter

### ISSUE THREAD

**Issue by norlinhenrik** [OCA/mis-builder#556]
I would like to have a report with only records **WITHOUT** any analytic account.

The Analytic Account Filter shows a list of analytic accounts. I would like to see **Undefined** in the end of the list.

**Comment by sbidoul** [comment]
With the generic `analytic_domain` we are adding in 16 (which we'll likely partially backport to 14 to some extent) this becomes easy to do.

**Comment by norlinhenrik** [comment]
https://github.com/OCA/mis-builder/pull/472 looks promising. Thank you! 👍
