### ISSUE TITLE
Can not update a multi kpi from the kpi line

### ISSUE THREAD

**Issue by gjlong68** [OCA/mis-builder#564]
mis-builder（V16）has a bug.

multi sub-kpi  nonsupport
user Error:Can not update a multi kpi from the kpi line

**Comment by sbidoul** [comment]
Can you provide step by step instructions to reproduce on runboat?

**Comment by gjlong68** [comment]
[Mis Builder Error.docx](https://github.com/OCA/mis-builder/files/11581429/Mis.Builder.Error.docx)
