### ISSUE TITLE
[16.0] mis_builder: hide mis.report.kpi in report when no data to show

### ISSUE THREAD

**Issue by rafaelbn** [OCA/mis-builder#566]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

- Problem: in many cases `mis.report.kpi` don't have dats, I mean, It doesn't have any `account.move.line` to show. Is different have "0" than have "nodata"

1.  Is you have in a KPI "0" is OK because you can navigate to moves
2. If there aren't any move for a KPI hide it

In some reports, fixed it could be great to have an option to hide all this empty KPI

**Describe the solution you'd like**

- Add an option in report to "Hide empty KPI". I'm not sure if this is possible technically in mis builder

**Describe alternatives you've considered**

- Well, there is not alternative. This is something we have in OCA Financial Reports for trial balance (hide lines with 0)

Could you @sbidoul indicate us possibilities and the way to implement it? We can make a PR 😄 

Thank you!

**Comment by sbidoul** [comment]
This should work today with the `hide_empty` style. Rows which don't have a value in any column will be hidden.

**Comment by sbidoul** [comment]
See also https://github.com/OCA/mis-builder/discussions/507

**Comment by rafaelbn** [comment]
Thank you very much! ❤️
