### ISSUE TITLE
Option to display only rows that are not 0

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/mis-builder#59]
In Spain it is required that the Profit & Loss and Balance Sheet presented to the authorities should only contain the lines that have some amount.

The P&L and BS are very large in extension, and many companies only use a small portion of the complete Chart of Accounts.

I am thinking on a flag at mis.report.kpi `hide rows with 0 values.` If all the columns in the row are 0 the line would not be listed.

**Comment by sbidoul** [comment]
That is implemented with styles: look for Hide Empty in style definitions.

Additionally, it does some hard work to distinguish no data (AccountingNone) from cells with transactions that sum to 0.

**Comment by JordiBForgeFlow** [comment]
OMG this is amazing!!

The spanish reports now have a readable format ;)

![image](https://user-images.githubusercontent.com/7683926/32962278-2d781c3a-cbcc-11e7-9872-fd9e9ef0ea6c.png)

![image](https://user-images.githubusercontent.com/7683926/32962281-30bcbc16-cbcc-11e7-811b-735ce691f97a.png)

![image](https://user-images.githubusercontent.com/7683926/32962290-3455398e-cbcc-11e7-9f83-c28d01ce2334.png)
