### ISSUE TITLE
Annotate data

### ISSUE THREAD

**Issue by SAnnabelle** [OCA/mis-builder#615]
Be able to annotate data on mis report, as is possible in standard Odoo reports (e.g. Balance Sheet).

![image](https://github.com/OCA/mis-builder/assets/96585378/58928c9d-7648-4f4a-81d3-6164fff52e4b)

**Comment by sbidoul** [comment]
Related to #159

**Comment by sbidoul** [comment]
So I'm closing and we can continue tracking this in #159
