### ISSUE TITLE
Manifest .py on mis_builder_budget

### ISSUE THREAD

**Issue by SIC-brunorocha** [OCA/mis-builder#631]
Hello Comunnity,

New to OCA, I hope I´m reporting in the correct place.
The mis_builder_budget on V17 branch as the incorrect version on the manifest.py file.
Is still labled as v16.
In this V17, the odoo.sh platform detects the version name during migration process, so even if the code does not need to change the version as to follow up the version.

Regards
Bruno

**Comment by sbidoul** [comment]
Hi, that is because, when you looked at it, the module was not migrated yet.
In this repo, we keep the previous version with installable = False in the manifest, because it makes review and traceability of migrations PR much easier.
