### ISSUE TITLE
[9.0] mis_builder - Tips for performance optimization?

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/mis-builder#69]
Hi!

I am using plenty of KPI's using syntax like `bale[][('account_id.tag_ids.name','=', '14300 Inventory')]`, but with quite a lot of history this seems to be a performance killer. @sbidoul do you have any recommendation based on your experience? Perhaps a better way to query based on account tags, or perhaps we need to add indices to the DB?

**Comment by JordiBForgeFlow** [comment]
cc @lreficent

**Comment by sbidoul** [comment]
`bale[('tag_ids.name','=', '14300 Inventory')]` should be much snappier :)

Everything that is done with the account filter is processed with a single query to database. When you do move line filters, then there is one query per filter.

**Comment by sbidoul** [comment]
These extended account selectors were added as a new feature in [mis builder 3.1](https://github.com/OCA/mis-builder/blob/11.0/mis_builder/CHANGES.rst#100311-2017-11-14).

**Comment by JordiBForgeFlow** [comment]
![giphy](https://user-images.githubusercontent.com/7683926/36024596-7d8454b8-0d90-11e8-9f53-f4b3d087d308.gif)

**Comment by JordiBForgeFlow** [comment]
@sbidoul Well that just made my week!! Thank you very much for the tip!

**Comment by sbidoul** [comment]
My pleasure :)
