### ISSUE TITLE
Instance-level toggle for Display detail by account

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#74]
On mis.report.instance, add a flag `no_auto_expand_accounts` that disables expansion of account details for all kpis.

This should allow the creation of templates that have account expansion on by default, while disabling it on specific reports that use the template.

cc/ @jbeficent

**Comment by pedrobaeza** [comment]
When I discussed this with @jbeficent about this, we talk about having a tri-valued field in the template for expressing the auto expand account feature:

* Always: It expands accounts for the template line.
* Never: Never expands accounts for the template line.
* Selectable: It expands depending on the flag put on the report.

I think this system is the most flexible one. If you limit to a flag, maybe there are some things that you want to expand and others be selectable, and it can't be done with your proposal.

**Comment by sbidoul** [comment]
@pedrobaeza @jbeficent interesting. Do you have example use cases where Always and Selectable would be combined?

**Comment by pedrobaeza** [comment]
Not right now in our official templates, but as this is a generic template builder, I think it can greatly improve having this feature with more or less the same effort.

**Comment by sbidoul** [comment]
Yes, it's not very complex indeed. Yet if there are no known uses cases I prefer to keep it as simple as possible. It can be added later when the use case arises.

**Comment by pedrobaeza** [comment]
The UI for user is going to be the same, so please don't discard it. If you want, I can make the PR.

**Comment by sbidoul** [comment]
No @pedrobaeza I disagree. It's more work (eg tests), and the UI is slightly more confusing for the user. So if there is no identified use case, let's not do it now. It's as easy to do it in several steps.

The account expansion mechanism is the most complex part of mis builder (and it's ad-hoc: I kind of plan to rework it and make it more generic in the future), So I want ot keep it as simple as possible.

Now if/when we have a clear use case I'm happy to do it as you propose.

**Comment by pedrobaeza** [comment]
OK, go ahead.
