### ISSUE TITLE
Missing images in README.rst

### ISSUE THREAD

**Issue by elicoidal** [OCA/mis-builder#76]
In following document, multiple images are missing: https://github.com/OCA/mis-builder/blob/10.0/mis_builder/README.rst

Not clear how to fix it by myself but let me know if I can help

**Comment by bealdav** [comment]
Hi @elicoidal, 

you can help for sure here. I explain
this code display the image in Odoo itself : in description field

```
.. figure:: static/description/ex_report.png
   :alt: Sample report configuration
```

This code display images in github rst viewer
```
.. figure:: mis_builder/static/description/ex_report.png
   :alt: Sample report configuration
```

The diff is the name of the module

Then if you add both syntax, all is displayed whatever the support

Nice i you can make a PR, thanks

**Comment by elicoidal** [comment]
@bealdav Thanks: not exactly what I meant. I understand how to render the rst but I do not know what kind of image @sbidoul would like (current directory is empty).
I can surely replicate the one similar to v8 (https://github.com/OCA/mis-builder/blob/8.0/mis_builder/README.rst) but was not sure that is what the maintainers would like to do

**Comment by bealdav** [comment]
Ok sorry for the misunderstood :-(

**Comment by elicoidal** [comment]
no harm at all :smile:

**Comment by sbidoul** [comment]
@elicoidal @bealdav see #77
