### ISSUE TITLE
date_range not available for version 11 of MIS Builder

### ISSUE THREAD

**Issue by houssine78** [OCA/mis-builder#88]
Hi There,
I'm wondering if date_range is still needed to have MIS builder installable on v11? It still on the dependency of Mis builder 11 but is hasn't been migrated to server-tools repo v11. Any clue about how to install Mis builder for Odoo 11 or I just need the date_range from v10?

Thanks for your help

@sbidoul

**Comment by sbidoul** [comment]
date_range has moved to https://github.com/oca/server-ux

or use `pip install odoo11-addon-mis_builder --pre`, which takes care of finding the dependencies

**Comment by houssine78** [comment]
thanks Stéphane! 😄
