### ISSUE TITLE
MIS Builder requieres date_range 

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/mis-builder#97]
Hi,

I knew this module and i decided implements it, but we have a problem: [`date_range`](https://github.com/OCA/mis-builder/blob/2bbdea16dad587c3650f21b72d4026d2c919f2c4/mis_builder/__manifest__.py#L18) is not available for Odoo 11.

What can we do?

**Comment by pedrobaeza** [comment]
Yes, it is in https://github.com/OCA/server-ux/tree/11.0/date_range.
