### ISSUE TITLE
[10.0] error in computed value

### ISSUE THREAD

**Issue by ovnicraft** [OCA/mis-builder#99]
I am testing mis_builder and i did this:

Simple template:
<img width="849" alt="captura de pantalla 2018-06-17 a la s 13 21 35" src="https://user-images.githubusercontent.com/31282/41510856-6a8cf68e-7231-11e8-93ca-2db7f5d87737.png">

Create report based on it:

<img width="844" alt="captura de pantalla 2018-06-17 a la s 13 22 29" src="https://user-images.githubusercontent.com/31282/41510865-908e4c3e-7231-11e8-95f6-a1aa597611b7.png">

Preview report and got this:

![prueba acida odoo](https://user-images.githubusercontent.com/31282/41510871-b8a7fd0a-7231-11e8-98c3-8830071d18aa.png)

I consider configuration is ok, but cant figure out how and where debug it to catch error.
I misconfigured something ?

**Comment by sbidoul** [comment]
Can you please hover the mouse over #ERR to see the error message?

**Comment by ovnicraft** [comment]
@sbidoul its syntax error on division, so i debug mis_safe_eval.py and catch the problem.
I load my report via csv files on module and codifications was an error so `/`  its `/01990`i dont konw why but i retype expression and works fine.
Thanks !
